In [435]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

# directory that contains agent_tools.py (must run before importing agent_tools)
_pkg = Path.cwd()
# print(_pkg)
if (_pkg / "agent_tools.py").is_file():
    pkg = _pkg
else:
    pkg = _pkg.parent  # typical: cwd is .../notebook, module is one level up

sys.path.insert(0, str(pkg.resolve()))

# Drop stale cache so edits to agent_tools.py are picked up without restarting the kernel
sys.modules.pop("agent_tools", None)
import agent_tools as at
# from agent_tools import AgentMemory

In [436]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 300)

# Input Data
Loading dataframe from a parquet or csv data located in path

In [437]:
path_data = '..\data\heloc_dataset_v1.parquet'

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\arifn\AppData\Local\Temp\ipykernel_33252\1931592331.py:1: SyntaxWarning: invalid escape sequence '\d'
  path_data = '..\data\heloc_dataset_v1.parquet'

In [438]:
try:
    df = pd.read_parquet(path_data)
except:
    try:
        df = pd.read_csv(path_data)
    except:
        raise ValueError(f"Failed to load data from {path_data}")

# Metadata
Setting metadata for column aliases, target column, feature column, time related column, data type (for data split), etc. The purpose of this aliases is so that we don't need to manually change the column name one-by-obne if we want to use different column for label, features, etc.  

col_time: datetime of event. e.g, date of application, click date, etc.  
col_target: column name of groundtruth label.  
cols_feat: column name of features used for training.  
col_day: column name of day-truncated col_time.  
col_month: column name of month-truncated col_time.  
col_type: column name of data type, whether the data is for train, test, valid, or hold-out sample (hoot, oot).  
col_score: column name of predicted probability score.
cols_feat_num: column name of numerical features.  
cols_feat_cat: column name of categorical features.  
cols_feat_time: column name of datetime features.

In [439]:
col_time = 'date'
col_target = 'label'
cols_feat = ['ExternalRiskEstimate', 'MSinceOldestTradeOpen',
       'MSinceMostRecentTradeOpen', 'AverageMInFile', 'NumSatisfactoryTrades',
       'NumTrades60Ever2DerogPubRec', 'NumTrades90Ever2DerogPubRec',
       'PercentTradesNeverDelq', 'MSinceMostRecentDelq',
       'MaxDelq2PublicRecLast12M', 'MaxDelqEver', 'NumTotalTrades',
       'NumTradesOpeninLast12M', 'PercentInstallTrades',
       'MSinceMostRecentInqexcl7days', 'NumInqLast6M', 'NumInqLast6Mexcl7days',
       'NetFractionRevolvingBurden', 'NetFractionInstallBurden',
       'NumRevolvingTradesWBalance', 'NumInstallTradesWBalance',
       'NumBank2NatlTradesWHighUtilization', 'PercentTradesWBalance']
col_day = 'day'
col_month = 'month'
col_type = 'type'
col_score = 'score'

In [440]:
df[col_day] = at.get_day_from_date(df, col_time)
df[col_month] = at.get_month_from_date(df, col_time)
cols_feat_num, cols_feat_cat, cols_feat_time = at.get_feature_dtype(df, cols_feat)

# EDA
Explarotary Data Analysis: Understanding the data quality, feature distribution, and labels before start modelling.  
In this session we also do preliminary filtering on the data by making sure that:  
1. Features has enough penetration: Missing rate less than 80%

## Missing rate of features

In [441]:
df_nan_rate = at.get_nan_rate(df, cols_feat)
display(df_nan_rate)

                          feature_name  missing_rate
0                 ExternalRiskEstimate           0.0
1                MSinceOldestTradeOpen           0.0
2            MSinceMostRecentTradeOpen           0.0
3                       AverageMInFile           0.0
4                NumSatisfactoryTrades           0.0
5          NumTrades60Ever2DerogPubRec           0.0
6          NumTrades90Ever2DerogPubRec           0.0
7               PercentTradesNeverDelq           0.0
8                 MSinceMostRecentDelq           0.0
9             MaxDelq2PublicRecLast12M           0.0
10                         MaxDelqEver           0.0
11                      NumTotalTrades           0.0
12              NumTradesOpeninLast12M           0.0
13                PercentInstallTrades           0.0
14        MSinceMostRecentInqexcl7days           0.0
15                        NumInqLast6M           0.0
16               NumInqLast6Mexcl7days           0.0
17          NetFractionRevolvingBurden           0.0
18            NetFractionInstallBurden           0.0
19          NumRevolvingTradesWBalance           0.0
20            NumInstallTradesWBalance           0.0
21  NumBank2NatlTradesWHighUtilization           0.0
22               PercentTradesWBalance           0.0

## Missing rate of features over period of time.

In [442]:
df_nan_rate_timely = at.get_nan_rate_timely(df, cols_feat, col_month)
display(df_nan_rate_timely)

                                   missing_rate                              \
time_period                              201501 201502 201503 201504 201505
feature_name
AverageMInFile                              0.0    0.0    0.0    0.0    0.0
ExternalRiskEstimate                        0.0    0.0    0.0    0.0    0.0
MSinceMostRecentDelq                        0.0    0.0    0.0    0.0    0.0
MSinceMostRecentInqexcl7days                0.0    0.0    0.0    0.0    0.0
MSinceMostRecentTradeOpen                   0.0    0.0    0.0    0.0    0.0
MSinceOldestTradeOpen                       0.0    0.0    0.0    0.0    0.0
MaxDelq2PublicRecLast12M                    0.0    0.0    0.0    0.0    0.0
MaxDelqEver                                 0.0    0.0    0.0    0.0    0.0
NetFractionInstallBurden                    0.0    0.0    0.0    0.0    0.0
NetFractionRevolvingBurden                  0.0    0.0    0.0    0.0    0.0
NumBank2NatlTradesWHighUtilization          0.0    0.0    0.0    0.0    0.0
NumInqLast6M                                0.0    0.0    0.0    0.0    0.0
NumInqLast6Mexcl7days                       0.0    0.0    0.0    0.0    0.0
NumInstallTradesWBalance                    0.0    0.0    0.0    0.0    0.0
NumRevolvingTradesWBalance                  0.0    0.0    0.0    0.0    0.0
NumSatisfactoryTrades                       0.0    0.0    0.0    0.0    0.0
NumTotalTrades                              0.0    0.0    0.0    0.0    0.0
NumTrades60Ever2DerogPubRec                 0.0    0.0    0.0    0.0    0.0
NumTrades90Ever2DerogPubRec                 0.0    0.0    0.0    0.0    0.0
NumTradesOpeninLast12M                      0.0    0.0    0.0    0.0    0.0
PercentInstallTrades                        0.0    0.0    0.0    0.0    0.0
PercentTradesNeverDelq                      0.0    0.0    0.0    0.0    0.0
PercentTradesWBalance                       0.0    0.0    0.0    0.0    0.0

                                                                              \
time_period                        201506 201507 201508 201509 201510 201511
feature_name
AverageMInFile                        0.0    0.0    0.0    0.0    0.0    0.0
ExternalRiskEstimate                  0.0    0.0    0.0    0.0    0.0    0.0
MSinceMostRecentDelq                  0.0    0.0    0.0    0.0    0.0    0.0
MSinceMostRecentInqexcl7days          0.0    0.0    0.0    0.0    0.0    0.0
MSinceMostRecentTradeOpen             0.0    0.0    0.0    0.0    0.0    0.0
MSinceOldestTradeOpen                 0.0    0.0    0.0    0.0    0.0    0.0
MaxDelq2PublicRecLast12M              0.0    0.0    0.0    0.0    0.0    0.0
MaxDelqEver                           0.0    0.0    0.0    0.0    0.0    0.0
NetFractionInstallBurden              0.0    0.0    0.0    0.0    0.0    0.0
NetFractionRevolvingBurden            0.0    0.0    0.0    0.0    0.0    0.0
NumBank2NatlTradesWHighUtilization    0.0    0.0    0.0    0.0    0.0    0.0
NumInqLast6M                          0.0    0.0    0.0    0.0    0.0    0.0
NumInqLast6Mexcl7days                 0.0    0.0    0.0    0.0    0.0    0.0
NumInstallTradesWBalance              0.0    0.0    0.0    0.0    0.0    0.0
NumRevolvingTradesWBalance            0.0    0.0    0.0    0.0    0.0    0.0
NumSatisfactoryTrades                 0.0    0.0    0.0    0.0    0.0    0.0
NumTotalTrades                        0.0    0.0    0.0    0.0    0.0    0.0
NumTrades60Ever2DerogPubRec           0.0    0.0    0.0    0.0    0.0    0.0
NumTrades90Ever2DerogPubRec           0.0    0.0    0.0    0.0    0.0    0.0
NumTradesOpeninLast12M                0.0    0.0    0.0    0.0    0.0    0.0
PercentInstallTrades                  0.0    0.0    0.0    0.0    0.0    0.0
PercentTradesNeverDelq                0.0    0.0    0.0    0.0    0.0    0.0
PercentTradesWBalance                 0.0    0.0    0.0    0.0    0.0    0.0


time_period                        201512
feature_name
AverageMInFile                        0.0
ExternalRiskEstimate                  0.0
MSinceMostRecentDelq                  0.0
MSinceMostRecentInqexcl7days          0.0
MSinceMostRecentTradeOpen             0.0
MSinceOldestTradeOpen                 0.0
MaxDelq2PublicRecLast12M              0.0
MaxDelqEver                           0.0
NetFractionInstallBurden              0.0
NetFractionRevolvingBurden            0.0
NumBank2NatlTradesWHighUtilization    0.0
NumInqLast6M                          0.0
NumInqLast6Mexcl7days                 0.0
NumInstallTradesWBalance              0.0
NumRevolvingTradesWBalance            0.0
NumSatisfactoryTrades                 0.0
NumTotalTrades                        0.0
NumTrades60Ever2DerogPubRec           0.0
NumTrades90Ever2DerogPubRec           0.0
NumTradesOpeninLast12M                0.0
PercentInstallTrades                  0.0
PercentTradesNeverDelq                0.0
PercentTradesWBalance                 0.0

# Split Data

In this section we split data into several data type:  

oot: Out of time sample, to check the performance of the model after development data.  
hoot: Historical out of time sample, to check the performance of the model before the development data.    
train: data sample for training model.  
valid: data sample for hyperparameter tuning.  
test: data sample for on-paper evaluation. 
In Summary, data type must follow thiss equence of event: oot --> train (t-3) | test | valid (t-2)  --> oot (t-1), where t is time notation.  

By looking at:
1. Distribution of target rate over period of time.  
2. Data count over the period of time.  
3. Number of positive label over the period of time.  

In the case of limited data, we should prioritize the data split with the following order:  
1. train (for model building: should have minimum 1000 data count) and oot data (for performance evaluation: should have min 300 data count).  
2. test.  
3. valid.  
4. hoot.

### Target (groundtruth) rate over period of time

In [443]:
df_stats_target_mean_per_month = at.get_timely_binary_target_rate(df, col_month, col_target)
display(df_stats_target_mean_per_month)

            mean  count  count_positive
month
201501  0.480534    899             432
201502  0.396552    812             322
201503  0.353726    899             318
201504  0.480460    870             418
201505  0.583982    899             525
201506  0.489655    870             426
201507  0.474972    899             427
201508  0.527374    895             472
201509  0.386905    840             325
201510  0.501152    868             435
201511  0.461905    840             388
201512  0.589862    868             512

In [444]:
at.plot_timely_binary_target_rate(df, col_month, col_target, 'target_rate_per_month.png')

In [445]:
oot_th = 201510
hoot_th = 201503

In [446]:
# Use the same integer scale for `col_period` and for oot_th / hoot_th (here: `month`).
df[col_type] = at.split_data(df, col_target, col_month, oot_th, hoot_th)

In [447]:
df[col_type].value_counts()

type
train    2636
hoot     2610
oot      2576
test     1319
valid    1318
Name: count, dtype: int64

Checking the consistency of the label distribution in each sample type.

In [448]:
df_target_rate_per_sample = at.get_target_rate_sample(df, col_type, col_target)
display(df_target_rate_per_sample)

       count      mean
type
hoot    2610  0.410728
oot     2576  0.518245
test    1319  0.492039
train   2636  0.491654
valid   1318  0.491654

# Feature transformation
1. Transform the feature into Weight of Evidence to handle non-monotinicity and inbalanced label.  
2. Fine tune the WoE if necessary based on: number of data each bin, number of positive label each bin, number of positive rate (target mean) each bin.

In [449]:
# Getting binningprocess object from otpbinning for woe transformation, woe statistics from training sample, and list of features that have issues during data transformation (missing feature, etc)
dict_bin, bp, df_binning_stats, binning_feature_issues = at.get_optimal_bin(
    df.loc[df[col_type] == "train"], cols_feat , col_target, cols_feat_cat=cols_feat_cat
)
display(df_binning_stats.sort_values(by='gini_power', ascending=False))

,name,dtype,status,selected,n_bins,iv,js,gini,quality_score,gini_power
11,NumTotalTrades,numerical,OPTIMAL,True,6,0.024596,0.003058,0.079225,0.002017,0.920775
2,MSinceMostRecentTradeOpen,numerical,OPTIMAL,True,6,0.035198,0.004382,0.100193,0.018778,0.899807
20,NumInstallTradesWBalance,numerical,OPTIMAL,True,6,0.042386,0.005271,0.108321,0.00329,0.891679
12,NumTradesOpeninLast12M,numerical,OPTIMAL,True,6,0.048713,0.006021,0.111746,0.010252,0.888254
4,NumSatisfactoryTrades,numerical,OPTIMAL,True,6,0.074214,0.009178,0.136911,0.064841,0.863089
6,NumTrades90Ever2DerogPubRec,numerical,OPTIMAL,True,3,0.126368,0.01552,0.143345,0.148225,0.856655
18,NetFractionInstallBurden,numerical,OPTIMAL,True,6,0.070341,0.008731,0.14392,0.031213,0.85608
19,NumRevolvingTradesWBalance,numerical,OPTIMAL,True,6,0.086865,0.010744,0.158586,0.160678,0.841414
16,NumInqLast6Mexcl7days,numerical,OPTIMAL,True,5,0.113001,0.013863,0.168369,0.106171,0.831631
15,NumInqLast6M,numerical,OPTIMAL,True,5,0.129148,0.015784,0.180347,0.059235,0.819653
13,PercentInstallTrades,numerical,OPTIMAL,True,6,0.139513,0.017158,0.19324,0.042333,0.80676
5,NumTrades60Ever2DerogPubRec,numerical,OPTIMAL,True,4,0.185248,0.0227,0.194911,0.175905,0.805089
10,MaxDelqEver,numerical,OPTIMAL,True,4,0.213936,0.026443,0.24403,0.385774,0.75597
21,NumBank2NatlTradesWHighUtilization,numerical,OPTIMAL,True,5,0.231613,0.028311,0.24725,0.385824,0.75275
1,MSinceOldestTradeOpen,numerical,OPTIMAL,True,6,0.241486,0.029316,0.256006,0.703672,0.743994
9,MaxDelq2PublicRecLast12M,numerical,OPTIMAL,True,4,0.285968,0.034801,0.275651,0.745532,0.724349
14,MSinceMostRecentInqexcl7days,numerical,OPTIMAL,True,6,0.336045,0.040369,0.283392,0.121017,0.716608
7,PercentTradesNeverDelq,numerical,OPTIMAL,True,6,0.329606,0.039886,0.288923,0.534294,0.711077
3,AverageMInFile,numerical,OPTIMAL,True,6,0.287889,0.035256,0.296096,0.520739,0.703904
8,MSinceMostRecentDelq,numerical,OPTIMAL,True,6,0.347992,0.042365,0.298473,0.56608,0.701527
22,PercentTradesWBalance,numerical,OPTIMAL,True,6,0.373355,0.045125,0.331807,0.657128,0.668193
17,NetFractionRevolvingBurden,numerical,OPTIMAL,True,6,0.525079,0.062422,0.378021,0.504932,0.621979
0,ExternalRiskEstimate,numerical,OPTIMAL,True,6,0.864614,0.101994,0.495183,0.26116,0.504817

In [450]:
# Getting binning table containing binning statistics for every feature. This statistics is used for fine-tuning if necessary.
df_binning_tables, features_issue_binning_tables = at.get_binning_tables_from_bp(bp, cols_feat)
display(df_binning_tables)

,Feature Name,Bin,Count,Count (%),Non-event,Event,Event rate,WoE,IV,JS
0,ExternalRiskEstimate,"(-inf, 64.50)",676,0.256449,525,151,0.223373,1.212731,0.333839,0.039347
1,ExternalRiskEstimate,"[64.50, 68.50)",364,0.138088,246,118,0.324176,0.70126,0.064889,0.007949
2,ExternalRiskEstimate,"[68.50, 70.50)",170,0.064492,102,68,0.400000,0.372078,0.008800,0.001094
3,ExternalRiskEstimate,"[70.50, 74.50)",341,0.129363,175,166,0.486804,0.019411,0.000049,0.000006
4,ExternalRiskEstimate,"[74.50, 80.50)",450,0.170713,158,292,0.648889,-0.647546,0.069545,0.008544
5,ExternalRiskEstimate,"[80.50, inf)",635,0.240895,134,501,0.788976,-1.352153,0.387492,0.045054
6,ExternalRiskEstimate,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
7,ExternalRiskEstimate,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
8,ExternalRiskEstimate,,2636,1.000000,1340,1296,0.491654,,0.864614,0.101994
9,MSinceOldestTradeOpen,"(-inf, 31.50)",148,0.056146,69,79,0.533784,-0.168728,0.001597,0.000199
10,MSinceOldestTradeOpen,"[31.50, 107.50)",341,0.129363,253,88,0.258065,1.022666,0.123645,0.014815
11,MSinceOldestTradeOpen,"[107.50, 134.50)",220,0.083460,140,80,0.363636,0.526229,0.022496,0.002780
12,MSinceOldestTradeOpen,"[134.50, 212.50)",971,0.368361,500,471,0.485067,0.026363,0.000256,0.000032
13,MSinceOldestTradeOpen,"[212.50, 273.50)",436,0.165402,198,238,0.545872,-0.217391,0.007800,0.000973
14,MSinceOldestTradeOpen,"[273.50, inf)",520,0.197269,180,340,0.653846,-0.669376,0.085692,0.010516
15,MSinceOldestTradeOpen,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
16,MSinceOldestTradeOpen,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
17,MSinceOldestTradeOpen,,2636,1.000000,1340,1296,0.491654,,0.241486,0.029316
18,MSinceMostRecentTradeOpen,"(-inf, 2.50)",585,0.221927,313,272,0.464957,0.107014,0.002537,0.000317
19,MSinceMostRecentTradeOpen,"[2.50, 3.50)",290,0.110015,169,121,0.417241,0.300721,0.009850,0.001227
20,MSinceMostRecentTradeOpen,"[3.50, 7.50)",746,0.283005,392,354,0.474531,0.068578,0.001330,0.000166
21,MSinceMostRecentTradeOpen,"[7.50, 9.50)",206,0.078149,103,103,0.500000,-0.033387,0.000087,0.000011
22,MSinceMostRecentTradeOpen,"[9.50, 16.50)",423,0.160470,201,222,0.524823,-0.132759,0.002827,0.000353
23,MSinceMostRecentTradeOpen,"[16.50, inf)",386,0.146434,162,224,0.580311,-0.357437,0.018567,0.002309
24,MSinceMostRecentTradeOpen,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
25,MSinceMostRecentTradeOpen,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
26,MSinceMostRecentTradeOpen,,2636,1.000000,1340,1296,0.491654,,0.035198,0.004382
27,AverageMInFile,"(-inf, 52.50)",562,0.213202,391,171,0.304270,0.793657,0.126863,0.015454
28,AverageMInFile,"[52.50, 65.50)",399,0.151366,248,151,0.378446,0.462762,0.031728,0.003931
29,AverageMInFile,"[65.50, 80.50)",541,0.205235,268,273,0.504621,-0.051872,0.000552,0.000069
30,AverageMInFile,"[80.50, 97.50)",498,0.188923,215,283,0.568273,-0.308196,0.017850,0.002222
31,AverageMInFile,"[97.50, 137.50)",476,0.180577,168,308,0.647059,-0.639523,0.071806,0.008826
32,AverageMInFile,"[137.50, inf)",160,0.060698,50,110,0.687500,-0.821844,0.039089,0.004753
33,AverageMInFile,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
34,AverageMInFile,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
35,AverageMInFile,,2636,1.000000,1340,1296,0.491654,,0.287889,0.035256
36,NumSatisfactoryTrades,"(-inf, 5.50)",191,0.072458,128,63,0.329843,0.675509,0.031689,0.003887
37,NumSatisfactoryTrades,"[5.50, 9.50)",236,0.089530,145,91,0.385593,0.432487,0.016431,0.002038
38,NumSatisfactoryTrades,"[9.50, 11.50)",158,0.059939,91,67,0.424051,0.27278,0.004423,0.000551
39,NumSatisfactoryTrades,"[11.50, 19.50)",776,0.294385,392,384,0.494845,-0.012768,0.000048,0.000006
40,NumSatisfactoryTrades,"[19.50, 39.50)",1105,0.419196,513,592,0.535747,-0.176618,0.013062,0.001631
41,NumSatisfactoryTrades,"[39.50, inf)",170,0.064492,71,99,0.582353,-0.365827,0.008562,0.001064
42,NumSatisfactoryTrades,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
43,NumSatisfactoryTrades,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
44,NumSatisfactoryTrades,,2636,1.000000,1340,1296,0.491654,,0.074214,0.009178
45,NumTrades60Ever2DerogPubRec,"(-inf, 0.50)",1860,0.705615,822,1038,0.558065,-0.266698,0.050004,0.006232
46,NumTrades60Ever2DerogPubRec,"[0.50, 1.50)",456,0.172989,289,167,0.366228,0.515046,0.044713,0.005528
47,NumTrades60Ever2DerogPubRec,"[1.50, 2.50)",162,0.061457,113,49,0.302469,0.802181,0.037317,0.004543
48,NumTrades60Ever2DerogPubRec,"[2.50, inf)",158,0.059939,116,42,0.265823,0.982534,0.053214,0.006396
49,NumTrades60Ever2DerogPubRec,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
50,NumTrades60Ever2DerogPubRec,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
51,NumTrades60Ever2DerogPubRec,,2636,1.000000,1340,1296,0.491654,,0.185248,0.022700
52,NumTrades90Ever2DerogPubRec,"(-inf, 0.50)",2078,0.788316,963,1115,0.536574,-0.179943,0.025495,0.003183
53,NumTrades90Ever2DerogPubRec,"[0.50, 1.50)",354,0.134294,234,120,0.338983,0.634442,0.052046,0.006399
54,NumTrades90Ever2DerogPubRec,"[1.50, inf)",204,0.077390,143,61,0.299020,0.818584,0.048827,0.005939
55,NumTrades90Ever2DerogPubRec,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
56,NumTrades90Ever2DerogPubRec,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
57,NumTrades90Ever2DerogPubRec,,2636,1.000000,1340,1296,0.491654,,0.126368,0.015520
58,PercentTradesNeverDelq,"(-inf, 63.50)",145,0.055008,91,54,0.372414,0.488488,0.012820,0.001587
59,PercentTradesNeverDelq,"[63.50, 75.50)",167,0.063354,133,34,0.203593,1.330602,0.097159,0.011321
60,PercentTradesNeverDelq,"[75.50, 83.50)",169,0.064112,124,45,0.266272,0.980232,0.056672,0.006813
61,PercentTradesNeverDelq,"[83.50, 90.50)",299,0.113429,196,103,0.344482,0.609999,0.040744,0.005015
62,PercentTradesNeverDelq,"[90.50, 95.50)",383,0.145296,214,169,0.441253,0.20269,0.005939,0.000741
63,PercentTradesNeverDelq,"[95.50, inf)",1473,0.558801,582,891,0.604888,-0.459261,0.116272,0.014408
64,PercentTradesNeverDelq,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
65,PercentTradesNeverDelq,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
66,PercentTradesNeverDelq,,2636,1.000000,1340,1296,0.491654,,0.329606,0.039886
67,MSinceMostRecentDelq,"(-inf, -3.50)",1319,0.500379,515,804,0.609553,-0.478819,0.113021,0.013994
68,MSinceMostRecentDelq,"[-3.50, 2.50)",170,0.064492,130,40,0.235294,1.145268,0.075760,0.008984
69,MSinceMostRecentDelq,"[2.50, 15.50)",520,0.197269,368,152,0.292308,0.850815,0.133870,0.016247
70,MSinceMostRecentDelq,"[15.50, 22.50)",148,0.056146,94,54,0.364865,0.520924,0.014837,0.001834
71,MSinceMostRecentDelq,"[22.50, 46.50)",294,0.111533,156,138,0.469388,0.089215,0.000886,0.000111
72,MSinceMostRecentDelq,"[46.50, inf)",185,0.070182,77,108,0.583784,-0.371713,0.009616,0.001195
73,MSinceMostRecentDelq,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
74,MSinceMostRecentDelq,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
75,MSinceMostRecentDelq,,2636,1.000000,1340,1296,0.491654,,0.347992,0.042365
76,MaxDelq2PublicRecLast12M,"(-inf, 1.50)",159,0.060319,92,67,0.421384,0.283709,0.004811,0.000599
77,MaxDelq2PublicRecLast12M,"[1.50, 5.50)",551,0.209029,402,149,0.270417,0.959119,0.177467,0.021370
78,MaxDelq2PublicRecLast12M,"[5.50, 6.50)",791,0.300076,407,384,0.485461,0.024784,0.000184,0.000023
79,MaxDelq2PublicRecLast12M,"[6.50, inf)",1135,0.430577,439,696,0.613216,-0.494237,0.103506,0.012808
80,MaxDelq2PublicRecLast12M,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
81,MaxDelq2PublicRecLast12M,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
82,MaxDelq2PublicRecLast12M,,2636,1.000000,1340,1296,0.491654,,0.285968,0.034801
83,MaxDelqEver,"(-inf, 3.50)",334,0.126707,212,122,0.365269,0.519178,0.033265,0.004112
84,MaxDelqEver,"[3.50, 5.50)",328,0.124431,219,109,0.332317,0.664337,0.052700,0.006469
85,MaxDelqEver,"[5.50, 6.50)",739,0.280349,427,312,0.422192,0.280394,0.021847,0.002722
86,MaxDelqEver,"[6.50, inf)",1235,0.468513,482,753,0.609717,-0.479508,0.106123,0.013140
87,MaxDelqEver,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
88,MaxDelqEver,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
89,MaxDelqEver,,2636,1.000000,1340,1296,0.491654,,0.213936,0.026443
90,NumTotalTrades,"(-inf, 8.50)",370,0.140364,211,159,0.429730,0.249567,0.008679,0.001082
91,NumTotalTrades,"[8.50, 11.50)",209,0.079287,113,96,0.459330,0.129653,0.001329,0.000166
92,NumTotalTrades,"[11.50, 21.50)",893,0.338771,460,433,0.484882,0.027102,0.000249,0.000031
93,NumTotalTrades,"[21.50, 24.50)",255,0.096737,129,126,0.494118,-0.009857,0.000009,0.000001
94,NumTotalTrades,"[24.50, 45.50)",769,0.291730,372,397,0.516255,-0.098429,0.002826,0.000353
95,NumTotalTrades,"[45.50, inf)",140,0.053111,55,85,0.607143,-0.468705,0.011503,0.001425
96,NumTotalTrades,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
97,NumTotalTrades,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
98,NumTotalTrades,,2636,1.000000,1340,1296,0.491654,,0.024596,0.003058
99,NumTradesOpeninLast12M,"(-inf, 0.50)",695,0.263657,309,386,0.555396,-0.255883,0.017206,0.002145
100,NumTradesOpeninLast12M,"[0.50, 1.50)",682,0.258725,341,341,0.500000,-0.033387,0.000288,0.000036
101,NumTradesOpeninLast12M,"[1.50, 2.50)",498,0.188923,254,244,0.489960,0.006779,0.000009,0.000001
102,NumTradesOpeninLast12M,"[2.50, 3.50)",357,0.135432,194,163,0.456583,0.140721,0.002674,0.000334
103,NumTradesOpeninLast12M,"[3.50, 5.50)",271,0.102807,152,119,0.439114,0.21137,0.004568,0.000570
104,NumTradesOpeninLast12M,"[5.50, inf)",133,0.050455,90,43,0.323308,0.705223,0.023967,0.002935
105,NumTradesOpeninLast12M,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
106,NumTradesOpeninLast12M,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
107,NumTradesOpeninLast12M,,2636,1.000000,1340,1296,0.491654,,0.048713,0.006021
108,PercentInstallTrades,"(-inf, 24.50)",897,0.340288,380,517,0.576366,-0.341259,0.039360,0.004896
109,PercentInstallTrades,"[24.50, 35.50)",658,0.249621,312,346,0.525836,-0.136823,0.004671,0.000583
110,PercentInstallTrades,"[35.50, 42.50)",323,0.122534,168,155,0.479876,0.047152,0.000272,0.000034
111,PercentInstallTrades,"[42.50, 46.50)",180,0.068285,95,85,0.472222,0.077839,0.000413,0.000052
112,PercentInstallTrades,"[46.50, 65.50)",443,0.168058,288,155,0.349887,0.586148,0.055876,0.006886
113,PercentInstallTrades,"[65.50, inf)",135,0.051214,97,38,0.281481,0.903738,0.038921,0.004706
114,PercentInstallTrades,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
115,PercentInstallTrades,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
116,PercentInstallTrades,,2636,1.000000,1340,1296,0.491654,,0.139513,0.017158
117,MSinceMostRecentInqexcl7days,"(-inf, -7.50)",202,0.076631,40,162,0.801980,-1.432104,0.136264,0.015712
118,MSinceMostRecentInqexcl7days,"[-7.50, 0.50)",1545,0.586115,949,596,0.385761,0.431781,0.107225,0.013300
119,MSinceMostRecentInqexcl7days,"[0.50, 1.50)",185,0.070182,92,93,0.502703,-0.044198,0.000137,0.000017
120,MSinceMostRecentInqexcl7days,"[1.50, 7.50)",427,0.161988,169,258,0.604215,-0.456448,0.033300,0.004127
121,MSinceMostRecentInqexcl7days,"[7.50, 12.50)",132,0.050076,44,88,0.666667,-0.726534,0.025476,0.003116
122,MSinceMostRecentInqexcl7days,"[12.50, inf)",145,0.055008,46,99,0.682759,-0.799865,0.033643,0.004097
123,MSinceMostRecentInqexcl7days,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
124,MSinceMostRecentInqexcl7days,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
125,MSinceMostRecentInqexcl7days,,2636,1.000000,1340,1296,0.491654,,0.336045,0.040369
126,NumInqLast6M,"(-inf, 0.50)",1045,0.396434,444,601,0.575120,-0.336157,0.044504,0.005537
127,NumInqLast6M,"[0.50, 1.50)",664,0.251897,344,320,0.481928,0.038934,0.000382,0.000048
128,NumInqLast6M,"[1.50, 2.50)",426,0.161608,223,203,0.476526,0.060579,0.000593,0.000074
129,NumInqLast6M,"[2.50, 4.50)",328,0.124431,201,127,0.387195,0.425731,0.022141,0.002747
130,NumInqLast6M,"[4.50, inf)",173,0.065630,128,45,0.260116,1.011981,0.061529,0.007379
131,NumInqLast6M,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
132,NumInqLast6M,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
133,NumInqLast6M,,2636,1.000000,1340,1296,0.491654,,0.129148,0.015784
134,NumInqLast6Mexcl7days,"(-inf, 0.50)",1096,0.415781,477,619,0.564781,-0.293976,0.035763,0.004454
135,NumInqLast6Mexcl7days,"[0.50, 1.50)",667,0.253035,341,326,0.488756,0.011598,0.000034,0.000004
136,NumInqLast6Mexcl7days,"[1.50, 2.50)",390,0.147951,204,186,0.476923,0.058986,0.000514,0.000064
137,NumInqLast6Mexcl7days,"[2.50, 4.50)",320,0.121396,200,120,0.375000,0.477439,0.027052,0.003350
138,NumInqLast6Mexcl7days,"[4.50, inf)",163,0.061836,118,45,0.276074,0.930635,0.049638,0.005990
139,NumInqLast6Mexcl7days,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
140,NumInqLast6Mexcl7days,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
141,NumInqLast6Mexcl7days,,2636,1.000000,1340,1296,0.491654,,0.113001,0.013863
142,NetFractionRevolvingBurden,"(-inf, 14.50)",979,0.371396,327,652,0.665986,-0.723471,0.187420,0.022930
143,NetFractionRevolvingBurden,"[14.50, 26.50)",356,0.135053,149,207,0.581461,-0.36216,0.017575,0.002185
144,NetFractionRevolvingBurden,"[26.50, 39.50)",347,0.131639,194,153,0.440922,0.204033,0.005452,0.000680
145,NetFractionRevolvingBurden,"[39.50, 65.50)",515,0.195372,316,199,0.386408,0.42905,0.035299,0.004379
146,NetFractionRevolvingBurden,"[65.50, 75.50)",164,0.062215,128,36,0.219512,1.235124,0.083673,0.009841
147,NetFractionRevolvingBurden,"[75.50, inf)",275,0.104325,226,49,0.178182,1.495328,0.195661,0.022407
148,NetFractionRevolvingBurden,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
149,NetFractionRevolvingBurden,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
150,NetFractionRevolvingBurden,,2636,1.000000,1340,1296,0.491654,,0.525079,0.062422
151,NetFractionInstallBurden,"(-inf, 7.50)",940,0.356601,428,512,0.544681,-0.212588,0.016084,0.002007
152,NetFractionInstallBurden,"[7.50, 33.50)",150,0.056904,55,95,0.633333,-0.579931,0.018707,0.002306
153,NetFractionInstallBurden,"[33.50, 61.50)",401,0.152124,199,202,0.503741,-0.04835,0.000356,0.000044
154,NetFractionInstallBurden,"[61.50, 72.50)",239,0.090668,133,106,0.443515,0.193523,0.003380,0.000422
155,NetFractionInstallBurden,"[72.50, 93.50)",673,0.255311,380,293,0.435364,0.226612,0.013031,0.001625
156,NetFractionInstallBurden,"[93.50, inf)",233,0.088392,145,88,0.377682,0.46601,0.018784,0.002327
157,NetFractionInstallBurden,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
158,NetFractionInstallBurden,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
159,NetFractionInstallBurden,,2636,1.000000,1340,1296,0.491654,,0.070341,0.008731
160,NumRevolvingTradesWBalance,"(-inf, 1.50)",510,0.193475,257,253,0.496078,-0.0177,0.000061,0.000008
161,NumRevolvingTradesWBalance,"[1.50, 2.50)",464,0.176024,191,273,0.588362,-0.390585,0.026603,0.003304
162,NumRevolvingTradesWBalance,"[2.50, 4.50)",774,0.293627,365,409,0.528424,-0.147205,0.006359,0.000794
163,NumRevolvingTradesWBalance,"[4.50, 6.50)",475,0.180197,262,213,0.448421,0.173665,0.005413,0.000676
164,NumRevolvingTradesWBalance,"[6.50, 7.50)",132,0.050076,79,53,0.401515,0.365769,0.006606,0.000821
165,NumRevolvingTradesWBalance,"[7.50, inf)",281,0.106601,186,95,0.338078,0.638483,0.041823,0.005141
166,NumRevolvingTradesWBalance,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
167,NumRevolvingTradesWBalance,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
168,NumRevolvingTradesWBalance,,2636,1.000000,1340,1296,0.491654,,0.086865,0.010744
169,NumInstallTradesWBalance,"(-inf, -3.50)",286,0.108498,116,170,0.594406,-0.415595,0.018538,0.002301
170,NumInstallTradesWBalance,"[-3.50, 1.50)",679,0.257587,331,348,0.512518,-0.083471,0.001795,0.000224
171,NumInstallTradesWBalance,"[1.50, 2.50)",756,0.286798,376,380,0.502646,-0.043969,0.000555,0.000069
172,NumInstallTradesWBalance,"[2.50, 3.50)",496,0.188164,269,227,0.457661,0.136374,0.003490,0.000436
173,NumInstallTradesWBalance,"[3.50, 4.50)",209,0.079287,123,86,0.411483,0.32445,0.008252,0.001027
174,NumInstallTradesWBalance,"[4.50, inf)",210,0.079666,125,85,0.404762,0.352275,0.009757,0.001213
175,NumInstallTradesWBalance,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
176,NumInstallTradesWBalance,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
177,NumInstallTradesWBalance,,2636,1.000000,1340,1296,0.491654,,0.042386,0.005271
178,NumBank2NatlTradesWHighUtilization,"(-inf, 0.50)",1367,0.518589,552,815,0.596196,-0.423027,0.091762,0.011385
179,NumBank2NatlTradesWHighUtilization,"[0.50, 1.50)",658,0.249621,376,282,0.428571,0.254295,0.016022,0.001997
180,NumBank2NatlTradesWHighUtilization,"[1.50, 2.50)",311,0.117982,194,117,0.376206,0.472297,0.025739,0.003188
181,NumBank2NatlTradesWHighUtilization,"[2.50, 3.50)",151,0.057284,104,47,0.311258,0.760856,0.031459,0.003840
182,NumBank2NatlTradesWHighUtilization,"[3.50, inf)",149,0.056525,114,35,0.234899,1.147463,0.066631,0.007900
183,NumBank2NatlTradesWHighUtilization,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
184,NumBank2NatlTradesWHighUtilization,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
185,NumBank2NatlTradesWHighUtilization,,2636,1.000000,1340,1296,0.491654,,0.231613,0.028311
186,PercentTradesWBalance,"(-inf, 44.50)",523,0.198407,162,361,0.690249,-0.834669,0.131589,0.015987
187,PercentTradesWBalance,"[44.50, 64.50)",739,0.280349,312,427,0.577808,-0.347168,0.033550,0.004173
188,PercentTradesWBalance,"[64.50, 75.50)",515,0.195372,279,236,0.458252,0.133993,0.003499,0.000437
189,PercentTradesWBalance,"[75.50, 84.50)",303,0.114947,181,122,0.402640,0.361089,0.014783,0.001838
190,PercentTradesWBalance,"[84.50, 89.50)",163,0.061836,108,55,0.337423,0.641411,0.024475,0.003008
191,PercentTradesWBalance,"[89.50, inf)",393,0.149090,298,95,0.241730,1.10983,0.165460,0.019682
192,PercentTradesWBalance,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
193,PercentTradesWBalance,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
194,PercentTradesWBalance,,2636,1.000000,1340,1296,0.491654,,0.373355,0.045125

In [451]:
at.draw_binning_tables_from_bp(bp, cols_feat, "./binning_figures")

['F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\ExternalRiskEstimate_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MSinceOldestTradeOpen_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MSinceMostRecentTradeOpen_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\AverageMInFile_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumSatisfactoryTrades_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumTrades60Ever2DerogPubRec_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumTrades90Ever2DerogPubRec_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\PercentTradesNeverDelq_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MSinceMostRecentDelq_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MaxDelq2PublicRecLast12M_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MaxDelqEver_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumTotalTrades_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumTradesOpeninLast12M_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\PercentInstallTrades_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\MSinceMostRecentInqexcl7days_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumInqLast6M_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumInqLast6Mexcl7days_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NetFractionRevolvingBurden_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NetFractionInstallBurden_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumRevolvingTradesWBalance_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumInstallTradesWBalance_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\NumBank2NatlTradesWHighUtilization_binning_table.png',
 'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\binning_figures\\PercentTradesWBalance_binning_table.png']

In [452]:
dict_bin

{'ExternalRiskEstimate': [64.5, 68.5, 70.5, 74.5, 80.5],
 'MSinceOldestTradeOpen': [31.5, 107.5, 134.5, 212.5, 273.5],
 'MSinceMostRecentTradeOpen': [2.5, 3.5, 7.5, 9.5, 16.5],
 'AverageMInFile': [52.5, 65.5, 80.5, 97.5, 137.5],
 'NumSatisfactoryTrades': [5.5, 9.5, 11.5, 19.5, 39.5],
 'NumTrades60Ever2DerogPubRec': [0.5, 1.5, 2.5],
 'NumTrades90Ever2DerogPubRec': [0.5, 1.5],
 'PercentTradesNeverDelq': [63.5, 75.5, 83.5, 90.5, 95.5],
 'MSinceMostRecentDelq': [-3.5, 2.5, 15.5, 22.5, 46.5],
 'MaxDelq2PublicRecLast12M': [1.5, 5.5, 6.5],
 'MaxDelqEver': [3.5, 5.5, 6.5],
 'NumTotalTrades': [8.5, 11.5, 21.5, 24.5, 45.5],
 'NumTradesOpeninLast12M': [0.5, 1.5, 2.5, 3.5, 5.5],
 'PercentInstallTrades': [24.5, 35.5, 42.5, 46.5, 65.5],
 'MSinceMostRecentInqexcl7days': [-7.5, 0.5, 1.5, 7.5, 12.5],
 'NumInqLast6M': [0.5, 1.5, 2.5, 4.5],
 'NumInqLast6Mexcl7days': [0.5, 1.5, 2.5, 4.5],
 'NetFractionRevolvingBurden': [14.5, 26.5, 39.5, 65.5, 75.5],
 'NetFractionInstallBurden': [7.5, 33.5, 61.5, 72.5, 93.5],
 'NumRevolvingTradesWBalance': [1.5, 2.5, 4.5, 6.5, 7.5],
 'NumInstallTradesWBalance': [-3.5, 1.5, 2.5, 3.5, 4.5],
 'NumBank2NatlTradesWHighUtilization': [0.5, 1.5, 2.5, 3.5],
 'PercentTradesWBalance': [44.5, 64.5, 75.5, 84.5, 89.5]}

In [453]:
# Fine-tune WOE if necessary. If not, skip it.
dict_bin = {'ExternalRiskEstimate': [64.5, 68.5, 70.5, 74.5, 80.5],
 'MSinceOldestTradeOpen': [31.5, 107.5, 134.5, 212.5, 273.5],
 'MSinceMostRecentTradeOpen': [2.5, 3.5, 7.5, 9.5, 16.5],
 'AverageMInFile': [52.5, 65.5, 80.5, 97.5, 137.5],
 'NumSatisfactoryTrades': [5.5, 9.5, 11.5, 19.5, 39.5],
 'NumTrades60Ever2DerogPubRec': [0.5, 1.5, 2.5],
 'NumTrades90Ever2DerogPubRec': [0.5, 1.5],
 'PercentTradesNeverDelq': [63.5, 75.5, 83.5, 90.5, 95.5],
 'MSinceMostRecentDelq': [-3.5, 2.5, 15.5, 22.5, 46.5],
 'MaxDelq2PublicRecLast12M': [1.5, 5.5, 6.5],
 'MaxDelqEver': [3.5, 5.5, 6.5],
 'NumTotalTrades': [8.5, 11.5, 21.5, 24.5, 45.5],
 'NumTradesOpeninLast12M': [0.5, 1.5, 2.5, 3.5, 5.5],
 'PercentInstallTrades': [24.5, 35.5, 42.5, 46.5, 65.5],
 'MSinceMostRecentInqexcl7days': [-7.5, 0.5, 1.5, 7.5, 12.5],
 'NumInqLast6M': [0.5, 1.5, 2.5, 4.5],
 'NumInqLast6Mexcl7days': [0.5, 1.5, 2.5, 4.5],
 'NetFractionRevolvingBurden': [14.5, 26.5, 39.5, 65.5, 75.5],
 'NetFractionInstallBurden': [7.5, 33.5, 61.5, 72.5, 93.5],
 'NumRevolvingTradesWBalance': [1.5, 2.5, 4.5, 6.5, 7.5],
 'NumInstallTradesWBalance': [-3.5, 1.5, 2.5, 3.5, 4.5],
 'NumBank2NatlTradesWHighUtilization': [0.5, 1.5, 2.5, 3.5],
 'PercentTradesWBalance': [44.5, 64.5, 75.5, 84.5, 89.5]}

bp, df_binning_stats, binning_feature_issues = at.modify_optimal_bin(df, dict_bin, cols_feat, col_target, cols_feat_cat)

In [454]:
df_binning_stats

,name,dtype,status,selected,n_bins,iv,js,gini,quality_score,gini_power
0,ExternalRiskEstimate,numerical,OPTIMAL,True,6,0.855131,0.10065,0.486913,0.314658,0.513087
1,MSinceOldestTradeOpen,numerical,OPTIMAL,True,6,0.194453,0.023794,0.236757,0.646593,0.763243
2,MSinceMostRecentTradeOpen,numerical,INFEASIBLE,True,1,0.0,0.0,0,0.0,1
3,AverageMInFile,numerical,OPTIMAL,True,6,0.253459,0.031103,0.27737,0.488868,0.72263
4,NumSatisfactoryTrades,numerical,OPTIMAL,True,6,0.084848,0.010519,0.153702,0.152694,0.846298
5,NumTrades60Ever2DerogPubRec,numerical,OPTIMAL,True,4,0.164937,0.020238,0.182989,0.045416,0.817011
6,NumTrades90Ever2DerogPubRec,numerical,OPTIMAL,True,3,0.121237,0.014839,0.139113,0.214827,0.860887
7,PercentTradesNeverDelq,numerical,OPTIMAL,True,6,0.311017,0.037853,0.285256,0.66836,0.714744
8,MSinceMostRecentDelq,numerical,OPTIMAL,True,6,0.261788,0.032016,0.258724,0.627953,0.741276
9,MaxDelq2PublicRecLast12M,numerical,OPTIMAL,True,4,0.291842,0.035675,0.287697,0.774936,0.712303
10,MaxDelqEver,numerical,OPTIMAL,True,4,0.205484,0.025434,0.23658,0.551634,0.76342
11,NumTotalTrades,numerical,OPTIMAL,True,6,0.044824,0.005581,0.116365,0.094704,0.883635
12,NumTradesOpeninLast12M,numerical,OPTIMAL,True,6,0.020236,0.002514,0.06686,0.000627,0.93314
13,PercentInstallTrades,numerical,OPTIMAL,True,6,0.084853,0.010435,0.135125,0.109813,0.864875
14,MSinceMostRecentInqexcl7days,numerical,OPTIMAL,True,6,0.231588,0.028501,0.238232,0.340535,0.761768
15,NumInqLast6M,numerical,OPTIMAL,True,5,0.080566,0.009945,0.145998,0.215582,0.854002
16,NumInqLast6Mexcl7days,numerical,OPTIMAL,True,5,0.073825,0.009126,0.140035,0.237864,0.859965
17,NetFractionRevolvingBurden,numerical,OPTIMAL,True,6,0.438965,0.052511,0.345332,0.865971,0.654668
18,NetFractionInstallBurden,numerical,INFEASIBLE,True,1,0.0,0.0,0,0.0,1
19,NumRevolvingTradesWBalance,numerical,INFEASIBLE,True,1,0.0,0.0,0,0.0,1
20,NumInstallTradesWBalance,numerical,OPTIMAL,True,6,0.015496,0.001933,0.06131,0.000098,0.93869
21,NumBank2NatlTradesWHighUtilization,numerical,OPTIMAL,True,5,0.217443,0.02666,0.240539,0.503423,0.759461
22,PercentTradesWBalance,numerical,OPTIMAL,True,6,0.27715,0.033844,0.286166,0.824152,0.713834

In [455]:
# Getting transformed woe data, name of columns containing woe data, and list of features that have issues during data transformation (missing feature, etc)
X_woe, cols_feat_woe, features_issue_woe = at.get_woe_from_bp(df, cols_feat, bp)

In [456]:
# Transform cols_feat to woe value and store it as new columns in the existing dataframe 
df[cols_feat_woe] = bp.transform(df[cols_feat], metric="woe")
display(df[cols_feat_woe])

,ExternalRiskEstimate_woe,MSinceOldestTradeOpen_woe,MSinceMostRecentTradeOpen_woe,AverageMInFile_woe,NumSatisfactoryTrades_woe,NumTrades60Ever2DerogPubRec_woe,NumTrades90Ever2DerogPubRec_woe,PercentTradesNeverDelq_woe,MSinceMostRecentDelq_woe,MaxDelq2PublicRecLast12M_woe,MaxDelqEver_woe,NumTotalTrades_woe,NumTradesOpeninLast12M_woe,PercentInstallTrades_woe,MSinceMostRecentInqexcl7days_woe,NumInqLast6M_woe,NumInqLast6Mexcl7days_woe,NetFractionRevolvingBurden_woe,NetFractionInstallBurden_woe,NumRevolvingTradesWBalance_woe,NumInstallTradesWBalance_woe,NumBank2NatlTradesWHighUtilization_woe,PercentTradesWBalance_woe
0,1.054241,-0.044439,2.220446e-16,-0.349456,-0.217190,0.882663,-0.172234,0.988806,0.986278,0.887186,0.576366,-0.100174,-0.095739,0.073863,0.372190,-0.247742,-0.233822,-0.007279,2.220446e-16,2.220446e-16,-0.092359,0.211931,0.057473
1,1.054241,0.897530,2.220446e-16,0.752955,0.568278,0.882663,0.925487,-0.475878,-0.405128,0.382841,-0.498298,0.364563,-0.103332,0.876635,0.372190,-0.247742,-0.233822,-0.622259,2.220446e-16,2.220446e-16,-0.097490,-0.401003,-0.605843
2,0.702694,0.897530,2.220446e-16,0.752955,0.433947,-0.248388,-0.172234,-0.475878,-0.405128,-0.568373,-0.498298,0.218546,0.131259,0.073863,0.372190,0.315639,0.352801,0.503967,2.220446e-16,2.220446e-16,-0.049402,0.211931,0.641080
3,0.702694,-0.044439,2.220446e-16,-0.054815,-0.217190,0.465254,0.536113,0.234620,-0.195169,0.084648,0.307768,-0.200571,0.121846,0.402916,0.372190,0.784107,0.352801,0.886401,2.220446e-16,2.220446e-16,0.258321,0.821699,0.948188
4,-1.477371,-0.577968,2.220446e-16,-0.604722,0.012186,-0.248388,-0.172234,-0.475878,-0.405128,-0.568373,-0.498298,0.045621,-0.103332,-0.155215,0.372190,-0.027298,-0.011080,0.503967,2.220446e-16,2.220446e-16,-0.092359,-0.401003,0.365942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10454,-0.036534,0.467000,2.220446e-16,0.258648,-0.217190,-0.248388,-0.172234,0.234620,-0.195169,0.084648,0.307768,0.045621,0.131259,-0.194113,-0.610937,-0.247742,-0.233822,-0.326912,2.220446e-16,2.220446e-16,-0.049402,-0.401003,0.948188
10455,0.702694,-0.044439,2.220446e-16,-0.054815,0.332151,-0.248388,-0.172234,0.234620,0.088063,0.084648,0.307768,0.045621,-0.103332,-0.077230,-0.224850,-0.027298,-0.011080,1.439089,2.220446e-16,2.220446e-16,-0.049402,0.211931,0.365942
10456,-0.036534,0.467000,2.220446e-16,0.258648,0.012186,0.465254,0.536113,-0.475878,-0.405128,0.084648,-0.498298,0.045621,-0.095739,-0.155215,-0.610937,0.315639,0.352801,-0.622259,2.220446e-16,2.220446e-16,-0.097490,-0.401003,-0.336695
10457,-0.036534,-0.280233,2.220446e-16,-0.604722,-0.399120,0.862088,0.925487,-0.475878,0.088063,0.084648,0.449788,-0.200571,-0.103332,-0.194113,-0.610937,-0.247742,-0.233822,-0.326912,2.220446e-16,2.220446e-16,-0.092359,-0.401003,-0.605843
10458,0.702694,0.265452,2.220446e-16,0.752955,0.568278,-0.248388,-0.172234,-0.475878,-0.405128,-0.568373,-0.498298,0.364563,0.016890,0.402916,-0.610937,0.315639,0.192617,0.886401,2.220446e-16,2.220446e-16,-0.092359,-0.401003,0.948188

# Feature Selection
In this section we implement different methodology for filtering the input feature so that only feature that has:
1. stability over time 
2. good performance  
can enter the model.

In [457]:
# Filtering for stability. We should as possible as we can minimize the target rate cross-over in feature bin over period of the time.
df_stats = at.get_timely_target_rate_feature_segment(df.loc[df[col_type]=='train'], cols_feat_woe, col_target, col_month)
display(df_stats)

,time period,feature name,segment,count data,count positive,positive rate
0,201504,ExternalRiskEstimate_woe,-1.477371,95,73,0.768421
1,201504,ExternalRiskEstimate_woe,-0.643091,74,47,0.635135
2,201504,ExternalRiskEstimate_woe,-0.036534,64,35,0.546875
3,201504,ExternalRiskEstimate_woe,0.414998,31,11,0.354839
4,201504,ExternalRiskEstimate_woe,0.702694,73,29,0.397260
...,...,...,...,...,...,...
661,201509,PercentTradesWBalance_woe,-0.336695,98,47,0.479592
662,201509,PercentTradesWBalance_woe,0.057473,82,34,0.414634
663,201509,PercentTradesWBalance_woe,0.365942,57,17,0.298246
664,201509,PercentTradesWBalance_woe,0.641080,31,9,0.290323
665,201509,PercentTradesWBalance_woe,0.948188,73,15,0.205479

In [458]:
# Pick only the desired features.
cols_feat_woe = at.set_value_list(['ExternalRiskEstimate_woe',
 'MSinceOldestTradeOpen_woe',
 'MSinceMostRecentTradeOpen_woe',
 'AverageMInFile_woe',
 'NumSatisfactoryTrades_woe',
 'NumTrades60Ever2DerogPubRec_woe',
 'NumTrades90Ever2DerogPubRec_woe',
 'PercentTradesNeverDelq_woe',
 'MSinceMostRecentDelq_woe',
 'MaxDelq2PublicRecLast12M_woe',
 'MaxDelqEver_woe',
 'NumTotalTrades_woe',
 'NumTradesOpeninLast12M_woe',
 'PercentInstallTrades_woe',
 'MSinceMostRecentInqexcl7days_woe',
 'NumInqLast6M_woe',
 'NumInqLast6Mexcl7days_woe',
 'NetFractionRevolvingBurden_woe',
 'NetFractionInstallBurden_woe',
 'NumRevolvingTradesWBalance_woe',
 'NumInstallTradesWBalance_woe',
 'NumBank2NatlTradesWHighUtilization_woe',
 'PercentTradesWBalance_woe'])

In [459]:

selected_feats_auc, feats_stats_auc = at.select_features_auc_max_corr(df.loc[df[col_type]=='train'], cols_feat_woe, col_target, max_corr=0.5)
display(feats_stats_auc)

,feature_name,max_correlation,auc_roc,standardized_auc_roc
0,ExternalRiskEstimate_woe,0.498863,0.252408,0.747592
1,PercentTradesWBalance_woe,0.406580,0.334096,0.665904
2,AverageMInFile_woe,0.341112,0.351952,0.648048
3,MSinceMostRecentInqexcl7days_woe,0.299108,0.372215,0.627785
4,NumBank2NatlTradesWHighUtilization_woe,0.498863,0.376375,0.623625
5,NumTrades60Ever2DerogPubRec_woe,0.442341,0.402545,0.597455
6,PercentInstallTrades_woe,0.390458,0.403380,0.596620
7,NumInqLast6M_woe,0.302512,0.409826,0.590174
8,NumSatisfactoryTrades_woe,0.348837,0.431545,0.568455
9,NumTradesOpeninLast12M_woe,0.302512,0.444127,0.555873
10,NumInstallTradesWBalance_woe,0.348837,0.445840,0.554160
11,MSinceMostRecentTradeOpen_woe,0.000000,0.500000,0.500000
12,NetFractionInstallBurden_woe,0.000000,0.500000,0.500000
13,NumRevolvingTradesWBalance_woe,0.000000,0.500000,0.500000

In [460]:
selected_feats_iv, feats_stats_iv = at.select_features_iv_max_corr(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(feats_stats_iv)

,feature_name,max_correlation,iv,auc_roc,standardized_auc_roc
0,ExternalRiskEstimate_woe,0.498863,0.809552,0.252408,0.747592
1,PercentTradesWBalance_woe,0.406580,0.342842,0.334096,0.665904
2,MSinceMostRecentInqexcl7days_woe,0.299108,0.315523,0.372215,0.627785
3,AverageMInFile_woe,0.341112,0.286387,0.351952,0.648048
4,NumBank2NatlTradesWHighUtilization_woe,0.498863,0.150515,0.376375,0.623625
5,PercentInstallTrades_woe,0.390458,0.120870,0.403380,0.596620
6,NumTrades60Ever2DerogPubRec_woe,0.442341,0.101090,0.402545,0.597455
7,NumInqLast6M_woe,0.302512,0.093200,0.409826,0.590174
8,NumSatisfactoryTrades_woe,0.348837,0.069875,0.431545,0.568455
9,NumTradesOpeninLast12M_woe,0.302512,0.034169,0.444127,0.555873
10,NumInstallTradesWBalance_woe,0.348837,0.033976,0.445840,0.554160

In [461]:
selected_feats_aic_fwd, df_stats_aic_fwd = at.select_features_aic_forward(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(df_stats_aic_fwd)

,step_number,added_feature_name,max_correlation,total_aic,delta_aic,roc_auc,gini
0,1,ExternalRiskEstimate_woe,0.000000,3122.544488,-532.992968,0.747592,0.495183
1,2,MSinceMostRecentInqexcl7days_woe,0.201530,3024.026068,-98.518419,0.771246,0.542492
2,3,PercentInstallTrades_woe,0.116182,2980.714645,-43.311423,0.781527,0.563054
3,4,MSinceOldestTradeOpen_woe,0.249673,2950.311292,-30.403353,0.786934,0.573868
4,5,PercentTradesWBalance_woe,0.406580,2937.466934,-12.844358,0.789942,0.579885
5,6,NumInstallTradesWBalance_woe,0.296758,2933.624595,-3.842339,0.791047,0.582093
6,7,NumBank2NatlTradesWHighUtilization_woe,0.498863,2932.460023,-1.164572,0.791784,0.583569
7,8,NumSatisfactoryTrades_woe,0.348837,2930.525260,-1.934762,0.792278,0.584555
8,9,NumTradesOpeninLast12M_woe,0.295831,2928.608004,-1.917257,0.793069,0.586139
9,10,NumTrades60Ever2DerogPubRec_woe,0.442341,2927.417300,-1.190703,0.793857,0.587713

In [462]:
selected_feats_aic_bwd, df_stats_aic_bwd = at.select_features_aic_backward(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(df_stats_aic_bwd)

,step_number,eliminated_feature_name,max_correlation,total_aic,delta_aic,roc_auc,gini
0,1,NumInqLast6M_woe,0.498863,2927.4173,-0.052366,0.793857,0.587713

In [463]:
selected_feats_bic_bwd, df_stats_bic_bwd = at.select_features_bic_backward(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(df_stats_bic_bwd)

,step_number,eliminated_feature_name,max_correlation,total_bic,delta_bic,roc_auc,gini
0,1,NumInqLast6M_woe,0.498863,2992.064497,-5.929384,0.793857,0.587713
1,2,NumInstallTradesWBalance_woe,0.498863,2987.329377,-4.735121,0.793008,0.586016
2,3,NumTrades60Ever2DerogPubRec_woe,0.498863,2982.862460,-4.466916,0.792571,0.585142
3,4,NumTradesOpeninLast12M_woe,0.498863,2977.751511,-5.110949,0.791842,0.583685
4,5,NumBank2NatlTradesWHighUtilization_woe,0.406580,2975.537858,-2.213654,0.790937,0.581874
5,6,NumSatisfactoryTrades_woe,0.406580,2972.729041,-2.808816,0.789942,0.579885

In [464]:
selected_feats_bic_fwd, df_stats_bic_fwd = at.select_features_bic_forward(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(selected_feats_bic_fwd)

['ExternalRiskEstimate_woe',
 'MSinceMostRecentInqexcl7days_woe',
 'PercentInstallTrades_woe',
 'MSinceOldestTradeOpen_woe',
 'PercentTradesWBalance_woe']

In [465]:
selected_feats_auc_fwd, df_stats_auc_fwd = at.select_features_auc_forward(df.loc[df[col_type]=='train'], cols_feat_woe, col_target)
display(selected_feats_auc_fwd)

['ExternalRiskEstimate_woe',
 'MSinceMostRecentInqexcl7days_woe',
 'PercentInstallTrades_woe',
 'MSinceOldestTradeOpen_woe']

# Model training

In [466]:
dict_statistics_auc, best_model_auc, importance_auc = at.train_logreg_l2_tune_cv(df, selected_feats_auc, col_target, col_type)
dict_statistics_iv, best_model_iv, importance_iv = at.train_logreg_l2_tune_cv(df, selected_feats_iv, col_target, col_type)
dict_statistics_aic_fwd, best_model_aic_fwd, importance_aic_fwd = at.train_logreg_l2_tune_cv(df, selected_feats_aic_fwd, col_target, col_type)
dict_statistics_aic_bwd, best_model_aic_bwd, importance_aic_bwd = at.train_logreg_l2_tune_cv(df, selected_feats_aic_bwd, col_target, col_type)
dict_statistics_bic_fwd, best_model_bic_fwd, importance_bic_fwd = at.train_logreg_l2_tune_cv(df, selected_feats_bic_fwd, col_target, col_type)
dict_statistics_bic_bwd, best_model_bic_bwd, importance_bic_bwd = at.train_logreg_l2_tune_cv(df, selected_feats_bic_bwd, col_target, col_type)
dict_statistics_auc_fwd, best_model_auc_fwd, importance_auc_fwd = at.train_logreg_l2_tune_cv(df, selected_feats_auc_fwd, col_target, col_type)

In [467]:
best_model_iv.get_params()

{'C': 0.1,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': 0.0,
 'max_iter': 10000,
 'n_jobs': None,
 'penalty': 'deprecated',
 'random_state': 42,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

# Model Prediction

In [468]:
df['proba_0_auc'], df['proba_1_auc'], feature_predict_issue = at.logreg_predict(df, best_model_auc, cols_feat_woe)
df['proba_0_iv'], df['proba_1_iv'], feature_predict_issue = at.logreg_predict(df, best_model_iv, cols_feat_woe)
df['proba_0_aic_fwd'], df['proba_1_aic_fwd'], feature_predict_issue = at.logreg_predict(df, best_model_aic_fwd, cols_feat_woe)
df['proba_0_aic_bwd'], df['proba_1_aic_bwd'], feature_predict_issue = at.logreg_predict(df, best_model_bic_fwd, cols_feat_woe)
df['proba_0_bic_fwd'], df['proba_1_bic_fwd'], feature_predict_issue = at.logreg_predict(df, best_model_aic_bwd, cols_feat_woe)
df['proba_0_bic_bwd'], df['proba_1_bic_bwd'], feature_predict_issue = at.logreg_predict(df, best_model_bic_bwd, cols_feat_woe)
df['proba_0_auc_fwd'], df['proba_1_auc_fwd'], feature_predict_issue = at.logreg_predict(df, best_model_auc_fwd, cols_feat_woe)

# Model Evaluation

In [469]:
cols_score = ['proba_1_auc', 'proba_1_iv', 'proba_1_aic_fwd', 'proba_1_aic_bwd', 'proba_1_bic_fwd', 'proba_1_bic_bwd', 'proba_1_auc_fwd']
df_stats_performance_per_scores = at.compare_scores_gini_auc(df, col_type, cols_score, col_target)
display(df_stats_performance_per_scores.transpose())

,proba_1_auc,proba_1_iv,proba_1_aic_fwd,proba_1_aic_bwd,proba_1_bic_fwd,proba_1_bic_bwd,proba_1_auc_fwd
gini_hoot,0.478653,0.484264,0.468612,0.459594,0.464801,0.455199,0.459130
gini_oot,0.522408,0.525259,0.513757,0.501277,0.509625,0.500315,0.498786
gini_test,0.520951,0.520045,0.517933,0.511736,0.495943,0.513115,0.507410
gini_train,0.532984,0.532763,0.536692,0.523927,0.507080,0.523695,0.520999
gini_valid,0.503934,0.501820,0.505270,0.495509,0.478165,0.497241,0.493659
auc_hoot,0.739327,0.742132,0.734306,0.729797,0.732400,0.727600,0.729565
auc_oot,0.761204,0.762630,0.756879,0.750638,0.754812,0.750157,0.749393
auc_test,0.760475,0.760022,0.758967,0.755868,0.747972,0.756558,0.753705
auc_train,0.766492,0.766381,0.768346,0.761963,0.753540,0.761848,0.760500
auc_valid,0.751967,0.750910,0.752635,0.747754,0.739082,0.748620,0.746830

In [470]:
df_stats_score_psi_over_time = at.get_timely_vars_psi(df.loc[df[col_type]=='train'], df.loc[df[col_type]!='train'], cols_score, col_month, n_bins=5)
display(df_stats_score_psi_over_time)

,proba_1_auc,proba_1_iv,proba_1_aic_fwd,proba_1_aic_bwd,proba_1_bic_fwd,proba_1_bic_bwd,proba_1_auc_fwd
time,,,,,,,
201501,0.007439,0.006492,0.005713,0.007352,0.010119,0.005813,0.009791
201502,0.590324,0.630399,0.591272,0.623866,0.638507,0.622457,0.627754
201503,0.040736,0.049013,0.053389,0.047161,0.050568,0.047020,0.041007
201504,0.019267,0.008732,0.014151,0.011403,0.021067,0.013919,0.023651
201505,0.041501,0.038088,0.049701,0.058162,0.028908,0.051932,0.049801
201506,0.012863,0.023017,0.016213,0.008366,0.017971,0.008897,0.016720
201507,0.016983,0.015013,0.016221,0.021147,0.016441,0.023441,0.021139
201508,0.007960,0.004396,0.005173,0.005636,0.008977,0.004208,0.007942
201509,0.029092,0.033943,0.033758,0.036466,0.025619,0.040431,0.040575
201510,0.006811,0.009253,0.006595,0.007396,0.009948,0.006324,0.006091
201511,0.009868,0.009580,0.006551,0.010204,0.009668,0.009542,0.008850
201512,0.003795,0.008538,0.008958,0.001467,0.010040,0.005514,0.000578

# Deep dive individual score
After we chose the score we want to use, we can do further analysis as the final check.

In [471]:
df_stats = at.get_score_predictive_power_data_type(df, 'proba_1_iv', col_type, col_target)
display(df_stats)

  time_period    aucroc      gini  count  count_positive  positive_rate
0        hoot  0.742132  0.484264   2610            1072       0.410728
1         oot  0.762630  0.525259   2576            1335       0.518245
2        test  0.760022  0.520045   1319             649       0.492039
3       train  0.766381  0.532763   2636            1296       0.491654
4       valid  0.750910  0.501820   1318             648       0.491654

In [472]:
df_stats = at.get_score_predictive_power_timely(df, 'proba_1_iv', col_month, col_target)
display(df_stats)

    time_period    aucroc      gini  count  count_positive  positive_rate
0        201501  0.744223  0.488446    899             432       0.480534
1        201502  0.698460  0.396920    812             322       0.396552
2        201503  0.772232  0.544464    899             318       0.353726
3        201504  0.730287  0.460574    870             418       0.480460
4        201505  0.769756  0.539511    899             525       0.583982
5        201506  0.745366  0.490732    870             426       0.489655
6        201507  0.786523  0.573046    899             427       0.474972
7        201508  0.817877  0.635753    895             472       0.527374
8        201509  0.692128  0.384257    840             325       0.386905
9        201510  0.734342  0.468684    868             435       0.501152
10       201511  0.771192  0.542383    840             388       0.461905
11       201512  0.781365  0.562730    868             512       0.589862

In [473]:
df_stats = at.get_score_predictive_power_data_type_bootstrap(df, 'proba_1_iv', col_type, col_target)

In [474]:
df_stats

,time_period,CI_5_gini,mean_gini,CI_95_gini,CI_5_aucroc,mean_auc,CI_95_aucroc,mean_positive_rate
0,hoot,0.312608,0.486931,0.650033,0.656304,0.743465,0.825016,0.41057
1,oot,0.360849,0.525988,0.675982,0.680425,0.762994,0.837991,0.51935
2,test,0.359194,0.517316,0.667965,0.679597,0.758658,0.833982,0.49123
3,train,0.382123,0.532160,0.675651,0.691061,0.766080,0.837826,0.49279
4,valid,0.336508,0.502923,0.658685,0.668254,0.751462,0.829343,0.49158

In [475]:
df_stats = at.compare_score_predictive_power_data_type_bootstrap(df, 'proba_1_iv', 'proba_1_auc', col_type, col_target)

In [476]:
df_stats

,time_period,champion_CI_5_gini,champion_mean_gini,champion_CI_95_gini,challenger_CI_5_gini,challenger_mean_gini,challenger_CI_95_gini,champion_CI_5_aucroc,champion_mean_auc,champion_CI_95_aucroc,challenger_CI_5_aucroc,challenger_mean_auc,challenger_CI_95_aucroc,mean_positive_rate
0,hoot,0.312608,0.486931,0.650033,0.304716,0.480346,0.648803,0.656304,0.743465,0.825016,0.652358,0.740173,0.824402,0.41057
1,oot,0.348880,0.522059,0.669530,0.346534,0.518862,0.667555,0.674440,0.761030,0.834765,0.673267,0.759431,0.833777,0.51786
2,test,0.353463,0.518004,0.662453,0.359250,0.519429,0.666112,0.676731,0.759002,0.831227,0.679625,0.759714,0.833056,0.49160
3,train,0.370675,0.531033,0.676454,0.366136,0.531707,0.676306,0.685338,0.765517,0.838227,0.683068,0.765854,0.838153,0.49267
4,valid,0.332361,0.502887,0.653186,0.338025,0.505373,0.657909,0.666181,0.751444,0.826593,0.669012,0.752686,0.828954,0.49252

In [477]:
df_stats = at.get_timely_feature_psi_woe(df.loc[df[col_type]=='train'], df.loc[df[col_type]!='train'], cols_feat_woe, col_month)

In [478]:
df_stats

       time                            feature_name       psi  count data
0    201501                ExternalRiskEstimate_woe  0.001409         899
1    201501               MSinceOldestTradeOpen_woe  0.003847         899
2    201501           MSinceMostRecentTradeOpen_woe  0.000000         899
3    201501                      AverageMInFile_woe  0.009819         899
4    201501               NumSatisfactoryTrades_woe  0.009620         899
5    201501         NumTrades60Ever2DerogPubRec_woe  0.004625         899
6    201501         NumTrades90Ever2DerogPubRec_woe  0.005780         899
7    201501              PercentTradesNeverDelq_woe  0.002614         899
8    201501                MSinceMostRecentDelq_woe  0.006516         899
9    201501            MaxDelq2PublicRecLast12M_woe  0.005187         899
10   201501                         MaxDelqEver_woe  0.005607         899
11   201501                      NumTotalTrades_woe  0.026357         899
12   201501              NumTradesOpeninLast12M_woe  0.025999         899
13   201501                PercentInstallTrades_woe  0.040218         899
14   201501        MSinceMostRecentInqexcl7days_woe  0.036749         899
15   201501                        NumInqLast6M_woe  0.020110         899
16   201501               NumInqLast6Mexcl7days_woe  0.016370         899
17   201501          NetFractionRevolvingBurden_woe  0.013125         899
18   201501            NetFractionInstallBurden_woe  0.000000         899
19   201501          NumRevolvingTradesWBalance_woe  0.000000         899
20   201501            NumInstallTradesWBalance_woe  0.006927         899
21   201501  NumBank2NatlTradesWHighUtilization_woe  0.003941         899
22   201501               PercentTradesWBalance_woe  0.016898         899
23   201502                ExternalRiskEstimate_woe  0.482852         812
24   201502               MSinceOldestTradeOpen_woe  1.234101         812
25   201502           MSinceMostRecentTradeOpen_woe  0.000000         812
26   201502                      AverageMInFile_woe  0.622394         812
27   201502               NumSatisfactoryTrades_woe  1.165566         812
28   201502         NumTrades60Ever2DerogPubRec_woe  0.129893         812
29   201502         NumTrades90Ever2DerogPubRec_woe  0.093969         812
30   201502              PercentTradesNeverDelq_woe  1.300419         812
31   201502                MSinceMostRecentDelq_woe  0.290223         812
32   201502            MaxDelq2PublicRecLast12M_woe  1.215060         812
33   201502                         MaxDelqEver_woe  0.836955         812
34   201502                      NumTotalTrades_woe  0.781868         812
35   201502              NumTradesOpeninLast12M_woe  0.506721         812
36   201502                PercentInstallTrades_woe  0.462806         812
37   201502        MSinceMostRecentInqexcl7days_woe  1.154144         812
38   201502                        NumInqLast6M_woe  0.320441         812
39   201502               NumInqLast6Mexcl7days_woe  0.315770         812
40   201502          NetFractionRevolvingBurden_woe  0.396314         812
41   201502            NetFractionInstallBurden_woe  0.000000         812
42   201502          NumRevolvingTradesWBalance_woe  0.000000         812
43   201502            NumInstallTradesWBalance_woe  0.995163         812
44   201502  NumBank2NatlTradesWHighUtilization_woe  0.217407         812
45   201502               PercentTradesWBalance_woe  0.725391         812
46   201503                ExternalRiskEstimate_woe  0.055859         899
47   201503               MSinceOldestTradeOpen_woe  0.012245         899
48   201503           MSinceMostRecentTradeOpen_woe  0.000000         899
49   201503                      AverageMInFile_woe  0.018898         899
50   201503               NumSatisfactoryTrades_woe  0.002070         899
51   201503         NumTrades60Ever2DerogPubRec_woe  0.020446         899
52   201503         NumTrades90Ever2DerogPubRec_woe  0.011564         899
53   201503              PercentTradesNeverDelq_woe  0.012246         899
54   201503                MSinceMostRecentDelq_woe  0.008040         899
55   201503            MaxDelq2PublicRecLast12M_woe  0.007395         899
56   201503                         MaxDelqEver_woe  0.004417         899
57   201503                      NumTotalTrades_woe  0.020725         899
58   201503              NumTradesOpeninLast12M_woe  0.019451         899
59   201503                PercentInstallTrades_woe  0.018202         899
60   201503        MSinceMostRecentInqexcl7days_woe  4.408195         899
61   201503                        NumInqLast6M_woe  0.008501         899
62   201503               NumInqLast6Mexcl7days_woe  0.004381         899
63   201503          NetFractionRevolvingBurden_woe  0.037215         899
64   201503            NetFractionInstallBurden_woe  0.000000         899
65   201503          NumRevolvingTradesWBalance_woe  0.000000         899
66   201503            NumInstallTradesWBalance_woe  0.008711         899
67   201503  NumBank2NatlTradesWHighUtilization_woe  0.051157         899
68   201503               PercentTradesWBalance_woe  0.023617         899
69   201504                ExternalRiskEstimate_woe  0.014038         416
70   201504               MSinceOldestTradeOpen_woe  0.014293         416
71   201504           MSinceMostRecentTradeOpen_woe  0.000000         416
72   201504                      AverageMInFile_woe  0.016210         416
73   201504               NumSatisfactoryTrades_woe  0.027299         416
74   201504         NumTrades60Ever2DerogPubRec_woe  0.003278         416
75   201504         NumTrades90Ever2DerogPubRec_woe  0.002402         416
76   201504              PercentTradesNeverDelq_woe  0.022080         416
77   201504                MSinceMostRecentDelq_woe  0.007926         416
78   201504            MaxDelq2PublicRecLast12M_woe  0.011198         416
79   201504                         MaxDelqEver_woe  0.005259         416
80   201504                      NumTotalTrades_woe  0.176427         416
81   201504              NumTradesOpeninLast12M_woe  0.032017         416
82   201504                PercentInstallTrades_woe  0.022178         416
83   201504        MSinceMostRecentInqexcl7days_woe  0.059992         416
84   201504                        NumInqLast6M_woe  0.002449         416
85   201504               NumInqLast6Mexcl7days_woe  0.007181         416
86   201504          NetFractionRevolvingBurden_woe  0.022840         416
87   201504            NetFractionInstallBurden_woe  0.000000         416
88   201504          NumRevolvingTradesWBalance_woe  0.000000         416
89   201504            NumInstallTradesWBalance_woe  0.015421         416
90   201504  NumBank2NatlTradesWHighUtilization_woe  0.007894         416
91   201504               PercentTradesWBalance_woe  0.005878         416
92   201505                ExternalRiskEstimate_woe  0.042818         459
93   201505               MSinceOldestTradeOpen_woe  0.046729         459
94   201505           MSinceMostRecentTradeOpen_woe  0.000000         459
95   201505                      AverageMInFile_woe  0.019263         459
96   201505               NumSatisfactoryTrades_woe  0.032844         459
97   201505         NumTrades60Ever2DerogPubRec_woe  0.006782         459
98   201505         NumTrades90Ever2DerogPubRec_woe  0.002197         459
99   201505              PercentTradesNeverDelq_woe  0.064987         459
100  201505                MSinceMostRecentDelq_woe  0.013851         459
101  201505            MaxDelq2PublicRecLast12M_woe  0.035895         459
102  201505                         MaxDelqEver_woe  0.013854         459
103  201505                      NumTotalTrades_woe  0.074104         459
104  201505              NumTradesOpeninLast12M_woe  0.017856         459
105  201505                PercentInstallTrades_woe  0.023658         459
106  201505        MSinceMostRecentInqexcl7days_woe  0.078206         459
107  201505                        NumInqLast6M_woe  0.004799         459
108  201505               NumInqLast6Mexcl7days_woe  0.006971         459
109  201505          NetFractionRevolvingBurden_woe  0.043396         459
110  201505            NetFractionInstallBurden_woe  0.000000         459
111  201505          NumRevolvingTradesWBalance_woe  0.000000         459
112  201505            NumInstallTradesWBalance_woe  0.012724         459
113  201505  NumBank2NatlTradesWHighUtilization_woe  0.011148         459
114  201505               PercentTradesWBalance_woe  0.085492         459
115  201506                ExternalRiskEstimate_woe  0.012436         433
116  201506               MSinceOldestTradeOpen_woe  0.016249         433
117  201506           MSinceMostRecentTradeOpen_woe  0.000000         433
118  201506                      AverageMInFile_woe  0.009660         433
119  201506               NumSatisfactoryTrades_woe  0.040620         433
120  201506         NumTrades60Ever2DerogPubRec_woe  0.007230         433
121  201506         NumTrades90Ever2DerogPubRec_woe  0.002117         433
122  201506              PercentTradesNeverDelq_woe  0.028667         433
123  201506                MSinceMostRecentDelq_woe  0.005065         433
124  201506            MaxDelq2PublicRecLast12M_woe  0.005788         433
125  201506                         MaxDelqEver_woe  0.007613         433
126  201506                      NumTotalTrades_woe  0.079774         433
127  201506              NumTradesOpeninLast12M_woe  0.039180         433
128  201506                PercentInstallTrades_woe  0.026550         433
129  201506        MSinceMostRecentInqexcl7days_woe  0.004874         433
130  201506                        NumInqLast6M_woe  0.014417         433
131  201506               NumInqLast6Mexcl7days_woe  0.012081         433
132  201506          NetFractionRevolvingBurden_woe  0.017453         433
133  201506            NetFractionInstallBurden_woe  0.000000         433
134  201506          NumRevolvingTradesWBalance_woe  0.000000         433
135  201506            NumInstallTradesWBalance_woe  0.014295         433
136  201506  NumBank2NatlTradesWHighUtilization_woe  0.007890         433
137  201506               PercentTradesWBalance_woe  0.004109         433
138  201507                ExternalRiskEstimate_woe  0.025098         455
139  201507               MSinceOldestTradeOpen_woe  0.012578         455
140  201507           MSinceMostRecentTradeOpen_woe  0.000000         455
141  201507                      AverageMInFile_woe  0.007675         455
142  201507               NumSatisfactoryTrades_woe  0.046495         455
143  201507         NumTrades60Ever2DerogPubRec_woe  0.022332         455
144  201507         NumTrades90Ever2DerogPubRec_woe  0.012071         455
145  201507              PercentTradesNeverDelq_woe  0.064491         455
146  201507                MSinceMostRecentDelq_woe  0.014335         455
147  201507            MaxDelq2PublicRecLast12M_woe  0.021009         455
148  201507                         MaxDelqEver_woe  0.018023         455
149  201507                      NumTotalTrades_woe  0.029206         455
150  201507              NumTradesOpeninLast12M_woe  0.042305         455
151  201507                PercentInstallTrades_woe  0.009473         455
152  201507        MSinceMostRecentInqexcl7days_woe  0.052809         455
153  201507                        NumInqLast6M_woe  0.036263         455
154  201507               NumInqLast6Mexcl7days_woe  0.031398         455
155  201507          NetFractionRevolvingBurden_woe  0.014988         455
156  201507            NetFractionInstallBurden_woe  0.000000         455
157  201507          NumRevolvingTradesWBalance_woe  0.000000         455
158  201507            NumInstallTradesWBalance_woe  0.032663         455
159  201507  NumBank2NatlTradesWHighUtilization_woe  0.005491         455
160  201507               PercentTradesWBalance_woe  0.006760         455
161  201508                ExternalRiskEstimate_woe  0.008413         438
162  201508               MSinceOldestTradeOpen_woe  0.027998         438
163  201508           MSinceMostRecentTradeOpen_woe  0.000000         438
164  201508                      AverageMInFile_woe  0.007363         438
165  201508               NumSatisfactoryTrades_woe  0.001522         438
166  201508         NumTrades60Ever2DerogPubRec_woe  0.023726         438
167  201508         NumTrades90Ever2DerogPubRec_woe  0.024617         438
168  201508              PercentTradesNeverDelq_woe  0.023266         438
169  201508                MSinceMostRecentDelq_woe  0.020819         438
170  201508            MaxDelq2PublicRecLast12M_woe  0.018777         438
171  201508                         MaxDelqEver_woe  0.019749         438
172  201508                      NumTotalTrades_woe  0.015403         438
173  201508              NumTradesOpeninLast12M_woe  0.006389         438
174  201508                PercentInstallTrades_woe  0.024456         438
175  201508        MSinceMostRecentInqexcl7days_woe  0.008689         438
176  201508                        NumInqLast6M_woe  0.018376         438
177  201508               NumInqLast6Mexcl7days_woe  0.015640         438
178  201508          NetFractionRevolvingBurden_woe  0.025618         438
179  201508            NetFractionInstallBurden_woe  0.000000         438
180  201508          NumRevolvingTradesWBalance_woe  0.000000         438
181  201508            NumInstallTradesWBalance_woe  0.008495         438
182  201508  NumBank2NatlTradesWHighUtilization_woe  0.005336         438
183  201508               PercentTradesWBalance_woe  0.030682         438
184  201509                ExternalRiskEstimate_woe  0.032423         436
185  201509               MSinceOldestTradeOpen_woe  0.053244         436
186  201509           MSinceMostRecentTradeOpen_woe  0.000000         436
187  201509                      AverageMInFile_woe  0.076873         436
188  201509               NumSatisfactoryTrades_woe  0.006215         436
189  201509         NumTrades60Ever2DerogPubRec_woe  0.014063         436
190  201509         NumTrades90Ever2DerogPubRec_woe  0.006542         436
191  201509              PercentTradesNeverDelq_woe  0.016902         436
192  201509                MSinceMostRecentDelq_woe  0.014076         436
193  201509            MaxDelq2PublicRecLast12M_woe  0.009437         436
194  201509                         MaxDelqEver_woe  0.019685         436
195  201509                      NumTotalTrades_woe  0.031739         436
196  201509              NumTradesOpeninLast12M_woe  0.009795         436
197  201509                PercentInstallTrades_woe  0.060114         436
198  201509        MSinceMostRecentInqexcl7days_woe  0.151285         436
199  201509                        NumInqLast6M_woe  0.010969         436
200  201509               NumInqLast6Mexcl7days_woe  0.009484         436
201  201509          NetFractionRevolvingBurden_woe  0.017468         436
202  201509            NetFractionInstallBurden_woe  0.000000         436
203  201509          NumRevolvingTradesWBalance_woe  0.000000         436
204  201509            NumInstallTradesWBalance_woe  0.032792         436
205  201509  NumBank2NatlTradesWHighUtilization_woe  0.003245         436
206  201509               PercentTradesWBalance_woe  0.032381         436
207  201510                ExternalRiskEstimate_woe  0.006889         868
208  201510               MSinceOldestTradeOpen_woe  0.073538         868
209  201510           MSinceMostRecentTradeOpen_woe  0.000000         868
210  201510                      AverageMInFile_woe  0.007265         868
211  201510               NumSatisfactoryTrades_woe  0.011078         868
212  201510         NumTrades60Ever2DerogPubRec_woe  0.003311         868
213  201510         NumTrades90Ever2DerogPubRec_woe  0.001460         868
214  201510              PercentTradesNeverDelq_woe  0.009175         868
215  201510                MSinceMostRecentDelq_woe  0.009080         868
216  201510            MaxDelq2PublicRecLast12M_woe  0.002717         868
217  201510                         MaxDelqEver_woe  0.002157         868
218  201510                      NumTotalTrades_woe  0.030324         868
219  201510              NumTradesOpeninLast12M_woe  0.005627         868
220  201510                PercentInstallTrades_woe  0.007019         868
221  201510        MSinceMostRecentInqexcl7days_woe  0.003788         868
222  201510                        NumInqLast6M_woe  0.005033         868
223  201510               NumInqLast6Mexcl7days_woe  0.006696         868
224  201510          NetFractionRevolvingBurden_woe  0.013525         868
225  201510            NetFractionInstallBurden_woe  0.000000         868
226  201510          NumRevolvingTradesWBalance_woe  0.000000         868
227  201510            NumInstallTradesWBalance_woe  0.015759         868
228  201510  NumBank2NatlTradesWHighUtilization_woe  0.015630         868
229  201510               PercentTradesWBalance_woe  0.003823         868
230  201511                ExternalRiskEstimate_woe  0.009036         840
231  201511               MSinceOldestTradeOpen_woe  0.010118         840
232  201511           MSinceMostRecentTradeOpen_woe  0.000000         840
233  201511                      AverageMInFile_woe  0.006783         840
234  201511               NumSatisfactoryTrades_woe  0.015785         840
235  201511         NumTrades60Ever2DerogPubRec_woe  0.005390         840
236  201511         NumTrades90Ever2DerogPubRec_woe  0.006495         840
237  201511              PercentTradesNeverDelq_woe  0.010925         840
238  201511                MSinceMostRecentDelq_woe  0.002825         840
239  201511            MaxDelq2PublicRecLast12M_woe  0.015946         840
240  201511                         MaxDelqEver_woe  0.014222         840
241  201511                      NumTotalTrades_woe  0.044673         840
242  201511              NumTradesOpeninLast12M_woe  0.003522         840
243  201511                PercentInstallTrades_woe  0.105648         840
244  201511        MSinceMostRecentInqexcl7days_woe  0.045854         840
245  201511                        NumInqLast6M_woe  0.010891         840
246  201511               NumInqLast6Mexcl7days_woe  0.006314         840
247  201511          NetFractionRevolvingBurden_woe  0.011525         840
248  201511            NetFractionInstallBurden_woe  0.000000         840
249  201511          NumRevolvingTradesWBalance_woe  0.000000         840
250  201511            NumInstallTradesWBalance_woe  0.021901         840
251  201511  NumBank2NatlTradesWHighUtilization_woe  0.006533         840
252  201511               PercentTradesWBalance_woe  0.031507         840
253  201512                ExternalRiskEstimate_woe  0.015617         868
254  201512               MSinceOldestTradeOpen_woe  0.004452         868
255  201512           MSinceMostRecentTradeOpen_woe  0.000000         868
256  201512                      AverageMInFile_woe  0.005592         868
257  201512               NumSatisfactoryTrades_woe  0.010259         868
258  201512         NumTrades60Ever2DerogPubRec_woe  0.013632         868
259  201512         NumTrades90Ever2DerogPubRec_woe  0.009822         868
260  201512              PercentTradesNeverDelq_woe  0.008575         868
261  201512                MSinceMostRecentDelq_woe  0.014789         868
262  201512            MaxDelq2PublicRecLast12M_woe  0.009567         868
263  201512                         MaxDelqEver_woe  0.004998         868
264  201512                      NumTotalTrades_woe  0.009377         868
265  201512              NumTradesOpeninLast12M_woe  0.011484         868
266  201512                PercentInstallTrades_woe  0.006231         868
267  201512        MSinceMostRecentInqexcl7days_woe  0.006211         868
268  201512                        NumInqLast6M_woe  0.047700         868

In [479]:
# df_stats = at.get_timely_psi(df.loc[df[col_type]=='train'], df.loc[df[col_type]!='train'], 'proba_1', col_month)

In [480]:
# df_stats

In [481]:
model_params = best_model_iv.get_params()

In [482]:
df_stats, scorecard = at.create_scorecard_model(df.loc[df[col_type]=='train'], cols_feat, model_params, col_target, bp)

In [483]:
display(df_stats)

,Variable,Bin id,Bin,Count,Count (%),Non-event,Event,Event rate,WoE,IV,JS,Coefficient,Points
0,ExternalRiskEstimate,0,"(-inf, 62.50)",522,0.198027,406,116,0.222222,1.219376,2.603110e-01,3.066187e-02,-0.270697,30.718233
1,ExternalRiskEstimate,1,"[62.50, 64.50)",154,0.058422,119,35,0.227273,1.190388,7.356576e-02,8.688551e-03,-0.270697,30.491821
2,ExternalRiskEstimate,2,"[64.50, 68.50)",364,0.138088,246,118,0.324176,0.701260,6.488948e-02,7.948966e-03,-0.270697,26.671397
3,ExternalRiskEstimate,3,"[68.50, 70.50)",170,0.064492,102,68,0.400000,0.372078,8.799746e-03,1.093667e-03,-0.270697,24.100265
4,ExternalRiskEstimate,4,"[70.50, 72.50)",181,0.068665,93,88,0.486188,0.021876,3.285179e-05,4.106392e-06,-0.270697,21.364949
5,ExternalRiskEstimate,5,"[72.50, 74.50)",160,0.060698,82,78,0.487500,0.016623,1.677043e-05,2.096280e-06,-0.270697,21.323925
6,ExternalRiskEstimate,6,"[74.50, 76.50)",156,0.059181,61,95,0.608974,-0.476390,1.323415e-02,1.638802e-03,-0.270697,17.473158
7,ExternalRiskEstimate,7,"[76.50, 80.50)",294,0.111533,97,197,0.670068,-0.741880,5.906707e-02,7.218589e-03,-0.270697,15.399504
8,ExternalRiskEstimate,8,"[80.50, 84.50)",255,0.096737,61,194,0.760784,-1.190371,1.239998e-01,1.464513e-02,-0.270697,11.896483
9,ExternalRiskEstimate,9,"[84.50, 87.50)",212,0.080425,42,170,0.801887,-1.431516,1.429076e-01,1.647913e-02,-0.270697,10.012982
10,ExternalRiskEstimate,10,"[87.50, inf)",168,0.063733,31,137,0.815476,-1.519381,1.254637e-01,1.432958e-02,-0.270697,9.326697
11,ExternalRiskEstimate,11,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.270697,21.194085
12,ExternalRiskEstimate,12,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.270697,21.194085
0,MSinceOldestTradeOpen,0,"(-inf, 31.50)",148,0.056146,69,79,0.533784,-0.168728,1.596888e-03,1.993745e-04,-0.312485,19.672763
1,MSinceOldestTradeOpen,1,"[31.50, 82.50)",189,0.071700,137,52,0.275132,0.935350,5.809960e-02,7.008774e-03,-0.312485,29.627575
2,MSinceOldestTradeOpen,2,"[82.50, 107.50)",152,0.057663,116,36,0.236842,1.136684,6.682497e-02,7.930608e-03,-0.312485,31.442883
3,MSinceOldestTradeOpen,3,"[107.50, 134.50)",220,0.083460,140,80,0.363636,0.526229,2.249587e-02,2.779981e-03,-0.312485,25.938773
4,MSinceOldestTradeOpen,4,"[134.50, 169.50)",452,0.171472,236,216,0.477876,0.055166,5.214733e-04,6.517589e-05,-0.312485,21.691487
5,MSinceOldestTradeOpen,5,"[169.50, 212.50)",519,0.196889,264,255,0.491329,0.001299,3.319932e-07,4.149914e-08,-0.312485,21.205793
6,MSinceOldestTradeOpen,6,"[212.50, 273.50)",436,0.165402,198,238,0.545872,-0.217391,7.800147e-03,9.731029e-04,-0.312485,19.234004
7,MSinceOldestTradeOpen,7,"[273.50, 367.50)",346,0.131259,124,222,0.641618,-0.615783,4.849843e-02,5.968302e-03,-0.312485,15.641941
8,MSinceOldestTradeOpen,8,"[367.50, inf)",174,0.066009,56,118,0.678161,-0.778720,3.835845e-02,4.677215e-03,-0.312485,14.172835
9,MSinceOldestTradeOpen,9,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.312485,21.194085
10,MSinceOldestTradeOpen,10,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.312485,21.194085
0,MSinceMostRecentTradeOpen,0,"(-inf, 2.50)",585,0.221927,313,272,0.464957,0.107014,2.536828e-03,3.169523e-04,-0.124953,21.579911
1,MSinceMostRecentTradeOpen,1,"[2.50, 3.50)",290,0.110015,169,121,0.417241,0.300721,9.850183e-03,1.226654e-03,-0.124953,22.278299
2,MSinceMostRecentTradeOpen,2,"[3.50, 7.50)",746,0.283005,392,354,0.474531,0.068578,1.329668e-03,1.661760e-04,-0.124953,21.441334
3,MSinceMostRecentTradeOpen,3,"[7.50, 9.50)",206,0.078149,103,103,0.500000,-0.033387,8.712799e-05,1.089049e-05,-0.124953,21.073712
4,MSinceMostRecentTradeOpen,4,"[9.50, 16.50)",423,0.160470,201,222,0.524823,-0.132759,2.827285e-03,3.531514e-04,-0.124953,20.715436
5,MSinceMostRecentTradeOpen,5,"[16.50, inf)",386,0.146434,162,224,0.580311,-0.357437,1.856669e-02,2.308560e-03,-0.124953,19.905390
6,MSinceMostRecentTradeOpen,6,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.124953,21.194085
7,MSinceMostRecentTradeOpen,7,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.124953,21.194085
0,AverageMInFile,0,"(-inf, 41.50)",326,0.123672,227,99,0.303681,0.796443,7.408044e-02,9.022819e-03,-0.512223,32.965224
1,AverageMInFile,1,"[41.50, 52.50)",236,0.089530,164,72,0.305085,0.789813,5.278520e-02,6.431828e-03,-0.512223,32.867237
2,AverageMInFile,2,"[52.50, 65.50)",399,0.151366,248,151,0.378446,0.462762,3.172801e-02,3.930988e-03,-0.512223,28.033537
3,AverageMInFile,3,"[65.50, 71.50)",219,0.083080,111,108,0.493151,-0.005988,2.979125e-06,3.723901e-07,-0.512223,21.105584
4,AverageMInFile,4,"[71.50, 80.50)",322,0.122155,157,165,0.512422,-0.083087,8.433827e-04,1.053925e-04,-0.512223,19.966094
5,AverageMInFile,5,"[80.50, 84.50)",144,0.054628,63,81,0.562500,-0.284701,4.408623e-03,5.492243e-04,-0.512223,16.986302
6,AverageMInFile,6,"[84.50, 97.50)",354,0.134294,152,202,0.570621,-0.317774,1.348359e-02,1.678393e-03,-0.512223,16.497498
7,AverageMInFile,7,"[97.50, 107.50)",186,0.070561,66,120,0.645161,-0.631224,2.735653e-02,3.363903e-03,-0.512223,11.864824
8,AverageMInFile,8,"[107.50, 137.50)",290,0.110015,102,188,0.648276,-0.644856,4.445788e-02,5.462906e-03,-0.512223,11.663346
9,AverageMInFile,9,"[137.50, inf)",160,0.060698,50,110,0.687500,-0.821844,3.908947e-02,4.753156e-03,-0.512223,9.047525
10,AverageMInFile,10,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.512223,21.194085
11,AverageMInFile,11,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.512223,21.194085
0,NumSatisfactoryTrades,0,"(-inf, 5.50)",191,0.072458,128,63,0.329843,0.675509,3.168897e-02,3.887486e-03,-0.624607,33.368342
1,NumSatisfactoryTrades,1,"[5.50, 9.50)",236,0.089530,145,91,0.385593,0.432487,1.643145e-02,2.038072e-03,-0.624607,28.988525
2,NumSatisfactoryTrades,2,"[9.50, 11.50)",158,0.059939,91,67,0.424051,0.272780,4.422557e-03,5.511121e-04,-0.624607,26.110222
3,NumSatisfactoryTrades,3,"[11.50, 19.50)",776,0.294385,392,384,0.494845,-0.012768,4.799367e-05,5.999168e-06,-0.624607,20.963980
4,NumSatisfactoryTrades,4,"[19.50, 23.50)",360,0.136571,173,187,0.519444,-0.111204,1.688705e-03,2.109794e-04,-0.624607,19.189926
5,NumSatisfactoryTrades,5,"[23.50, 39.50)",745,0.282625,340,405,0.543624,-0.208328,1.224318e-02,1.527636e-03,-0.624607,17.439514
6,NumSatisfactoryTrades,6,"[39.50, inf)",170,0.064492,71,99,0.582353,-0.365827,8.561747e-03,1.064290e-03,-0.624607,14.601020
7,NumSatisfactoryTrades,7,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.624607,21.194085
8,NumSatisfactoryTrades,8,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.624607,21.194085
0,NumTrades60Ever2DerogPubRec,0,"(-inf, 0.50)",1860,0.705615,822,1038,0.558065,-0.266698,5.000397e-02,6.232038e-03,-0.164356,19.929318
1,NumTrades60Ever2DerogPubRec,1,"[0.50, 1.50)",456,0.172989,289,167,0.366228,0.515046,4.471299e-02,5.528156e-03,-0.164356,23.636600
2,NumTrades60Ever2DerogPubRec,2,"[1.50, 2.50)",162,0.061457,113,49,0.302469,0.802181,3.731721e-02,4.543472e-03,-0.164356,24.998285
3,NumTrades60Ever2DerogPubRec,3,"[2.50, inf)",158,0.059939,116,42,0.265823,0.982534,5.321378e-02,6.396447e-03,-0.164356,25.853578
4,NumTrades60Ever2DerogPubRec,4,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.164356,21.194085
5,NumTrades60Ever2DerogPubRec,5,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.164356,21.194085
0,NumTrades90Ever2DerogPubRec,0,"(-inf, 0.50)",2078,0.788316,963,1115,0.536574,-0.179943,2.549487e-02,3.182566e-03,-0.009746,21.143481
1,NumTrades90Ever2DerogPubRec,1,"[0.50, 1.50)",354,0.134294,234,120,0.338983,0.634442,5.204602e-02,6.398790e-03,-0.009746,21.372504
2,NumTrades90Ever2DerogPubRec,2,"[1.50, inf)",204,0.077390,143,61,0.299020,0.818584,4.882731e-02,5.938518e-03,-0.009746,21.424288
3,NumTrades90Ever2DerogPubRec,3,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.009746,21.194085
4,NumTrades90Ever2DerogPubRec,4,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.009746,21.194085
0,PercentTradesNeverDelq,0,"(-inf, 63.50)",145,0.055008,91,54,0.372414,0.488488,1.281978e-02,1.586728e-03,-0.276978,25.098032
1,PercentTradesNeverDelq,1,"[63.50, 75.50)",167,0.063354,133,34,0.203593,1.330602,9.715941e-02,1.132148e-02,-0.276978,31.828111
2,PercentTradesNeverDelq,2,"[75.50, 83.50)",169,0.064112,124,45,0.266272,0.980232,5.667221e-02,6.813374e-03,-0.276978,29.027995
3,PercentTradesNeverDelq,3,"[83.50, 90.50)",299,0.113429,196,103,0.344482,0.609999,4.074385e-02,5.015460e-03,-0.276978,26.069129
4,PercentTradesNeverDelq,4,"[90.50, 95.50)",383,0.145296,214,169,0.441253,0.202690,5.938878e-03,7.410915e-04,-0.276978,22.813964
5,PercentTradesNeverDelq,5,"[95.50, 97.50)",206,0.078149,89,117,0.567961,-0.306925,7.323180e-03,9.118213e-04,-0.276978,18.741176
6,PercentTradesNeverDelq,6,"[97.50, inf)",1267,0.480653,493,774,0.610892,-0.484450,1.110900e-01,1.375204e-02,-0.276978,17.322414
7,PercentTradesNeverDelq,7,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.276978,21.194085
8,PercentTradesNeverDelq,8,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.276978,21.194085
0,MSinceMostRecentDelq,0,"(-inf, -3.50)",1319,0.500379,515,804,0.609553,-0.478819,1.130215e-01,1.399426e-02,-0.646253,12.265576
1,MSinceMostRecentDelq,1,"[-3.50, 2.50)",170,0.064492,130,40,0.235294,1.145268,7.576031e-02,8.984212e-03,-0.646253,42.549810
2,MSinceMostRecentDelq,2,"[2.50, 15.50)",520,0.197269,368,152,0.292308,0.850815,1.338698e-01,1.624659e-02,-0.646253,37.059175
3,MSinceMostRecentDelq,3,"[15.50, 22.50)",148,0.056146,94,54,0.364865,0.520924,1.483726e-02,1.833967e-03,-0.646253,30.907710
4,MSinceMostRecentDelq,4,"[22.50, 32.50)",138,0.052352,78,60,0.434783,0.228977,2.727728e-03,3.402231e-04,-0.646253,25.463806
5,MSinceMostRecentDelq,5,"[32.50, 46.50)",156,0.059181,78,78,0.500000,-0.033387,6.598042e-05,8.247170e-06,-0.646253,20.571520
6,MSinceMostRecentDelq,6,"[46.50, inf)",185,0.070182,77,108,0.583784,-0.371713,9.616451e-03,1.195183e-03,-0.646253,14.262784
7,MSinceMostRecentDelq,7,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.646253,21.194085
8,MSinceMostRecentDelq,8,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.646253,21.194085
0,MaxDelq2PublicRecLast12M,0,"(-inf, 1.50)",159,0.060319,92,67,0.421384,0.283709,4.811473e-03,5.994251e-04,0.006846,21.138045
1,MaxDelq2PublicRecLast12M,1,"[1.50, 5.50)",551,0.209029,402,149,0.270417,0.959119,1.774666e-01,2.137033e-02,0.006846,21.004633
2,MaxDelq2PublicRecLast12M,2,"[5.50, 6.50)",791,0.300076,407,384,0.485461,0.024784,1.842674e-04,2.303283e-05,0.006846,21.189189
3,MaxDelq2PublicRecLast12M,3,"[6.50, inf)",1135,0.430577,439,696,0.613216,-0.494237,1.035057e-01,1.280811e-02,0.006846,21.291710
4,MaxDelq2PublicRecLast12M,4,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.006846,21.194085
5,MaxDelq2PublicRecLast12M,5,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.006846,21.194085
0,MaxDelqEver,0,"(-inf, 3.50)",334,0.126707,212,122,0.365269,0.519178,3.326539e-02,4.112093e-03,0.237211,17.640591
1,MaxDelqEver,1,"[3.50, 5.50)",328,0.124431,219,109,0.332317,0.664337,5.270044e-02,6.469027e-03,0.237211,16.647059
2,MaxDelqEver,2,"[5.50, 6.50)",739,0.280349,427,312,0.422192,0.280394,2.184716e-02,2.721984e-03,0.237211,19.274941
3,MaxDelqEver,3,"[6.50, inf)",1235,0.468513,482,753,0.609717,-0.479508,1.061233e-01,1.313977e-02,0.237211,24.476059
4,MaxDelqEver,4,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.237211,21.194085
5,MaxDelqEver,5,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.237211,21.194085
0,NumTotalTrades,0,"(-inf, 8.50)",370,0.140364,211,159,0.429730,0.249567,8.679314e-03,1.082107e-03,-0.284843,23.245233
1,NumTotalTrades,1,"[8.50, 11.50)",209,0.079287,113,96,0.459330,0.129653,1.329495e-03,1.660705e-04,-0.284843,22.259678
2,NumTotalTrades,2,"[11.50, 16.50)",444,0.168437,229,215,0.484234,0.029697,1.484985e-04,1.856163e-05,-0.284843,21.438159
3,NumTotalTrades,3,"[16.50, 21.50)",449,0.170334,231,218,0.485523,0.024536,1.025144e-04,1.281397e-05,-0.284843,21.395739
4,NumTotalTrades,4,"[21.50, 24.50)",255,0.096737,129,126,0.494118,-0.009857,9.398836e-06,1.174850e-06,-0.284843,21.113076
5,NumTotalTrades,5,"[24.50, 29.50)",306,0.116085,149,157,0.513072,-0.085687,8.524048e-04,1.065180e-04,-0.284843,20.489842
6,NumTotalTrades,6,"[29.50, 45.50)",463,0.175645,223,240,0.518359,-0.106854,2.005362e-03,2.505510e-04,-0.284843,20.315868
7,NumTotalTrades,7,"[45.50, inf)",140,0.053111,55,85,0.607143,-0.468705,1.150279e-02,1.424831e-03,-0.284843,17.341877
8,NumTotalTrades,8,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.284843,21.194085
9,NumTotalTrades,9,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.284843,21.194085
0,NumTradesOpeninLast12M,0,"(-inf, 0.50)",695,0.263657,309,386,0.555396,-0.255883,1.720622e-02,2.144929e-03,-0.129456,20.238283
1,NumTradesOpeninLast12M,1,"[0.50, 1.50)",682,0.258725,341,341,0.500000,-0.033387,2.884529e-04,3.605493e-05,-0.129456,21.069374
2,NumTradesOpeninLast12M,2,"[1.50, 2.50)",498,0.188923,254,244,0.489960,0.006779,8.681450e-06,1.085179e-06,-0.129456,21.219407
3,NumTradesOpeninLast12M,3,"[2.50, 3.50)",357,0.135432,194,163,0.456583,0.140721,2.674333e-03,3.340161e-04,-0.129456,21.719721
4,NumTradesOpeninLast12M,4,"[3.50, 5.50)",271,0.102807,152,119,0.439114,0.211370,4.568097e-03,5.699515e-04,-0.129456,21.983617
5,NumTradesOpeninLast12M,5,"[5.50, inf)",133,0.050455,90,43,0.323308,0.705223,2.396711e-02,2.935310e-03,-0.129456,23.828309
6,NumTradesOpeninLast12M,6,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.129456,21.194085
7,NumTradesOpeninLast12M,7,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.129456,21.194085
0,PercentInstallTrades,0,"(-inf, 24.50)",897,0.340288,380,517,0.576366,-0.341259,3.935997e-02,4.896261e-03,-0.568601,15.595278
1,PercentInstallTrades,1,"[24.50, 35.50)",658,0.249621,312,346,0.525836,-0.136823,4.671054e-03,5.834267e-04,-0.568601,18.949326
2,PercentInstallTrades,2,"[35.50, 42.50)",323,0.122534,168,155,0.479876,0.047152,2.722722e-04,3.403087e-05,-0.568601,21.967674
3,PercentInstallTrades,3,"[42.50, 46.50)",180,0.068285,95,85,0.472222,0.077839,4.132532e-04,5.164362e-05,-0.568601,22.471132
4,PercentInstallTrades,4,"[46.50, 65.50)",443,0.168058,288,155,0.349887,0.586148,5.587553e-02,6.886143e-03,-0.568601,30.810637
5,PercentInstallTrades,5,"[65.50, inf)",135,0.051214,97,38,0.281481,0.903738,3.892134e-02,4.706080e-03,-0.568601,36.021119
6,PercentInstallTrades,6,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.568601,21.194085
7,PercentInstallTrades,7,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.568601,21.194085
0,MSinceMostRecentInqexcl7days,0,"(-inf, -7.50)",202,0.076631,40,162,0.801980,-1.432104,1.362636e-01,1.571201e-02,-0.612003,-4.094988
1,MSinceMostRecentInqexcl7days,1,"[-7.50, -3.50)",460,0.174507,284,176,0.382609,0.445103,3.388919e-02,4.201523e-03,-0.612003,29.054023
2,MSinceMostRecentInqexcl7days,2,"[-3.50, 0.50)",1085,0.411608,665,420,0.387097,0.426145,7.337991e-02,9.103708e-03,-0.612003,28.719251
3,MSinceMostRecentInqexcl7days,3,"[0.50, 1.50)",185,0.070182,92,93,0.502703,-0.044198,1.371260e-04,1.713935e-05,-0.612003,20.413607
4,MSinceMostRecentInqexcl7days,4,"[1.50, 7.50)",427,0.161988,169,258,0.604215,-0.456448,3.330001e-02,4.126738e-03,-0.612003,13.133815
5,MSinceMostRecentInqexcl7days,5,"[7.50, 12.50)",132,0.050076,44,88,0.666667,-0.726534,2.547622e-02,3.116286e-03,-0.612003,8.364446
6,MSinceMostRecentInqexcl7days,6,"[12.50, inf)",145,0.055008,46,99,0.682759,-0.799865,3.364277e-02,4.096709e-03,-0.612003,7.069512
7,MSinceMostRecentInqexcl7days,7,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.612003,21.194085
8,MSinceMostRecentInqexcl7days,8,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.612003,21.194085
0,NumInqLast6M,0,"(-inf, 0.50)",1045,0.396434,444,601,0.575120,-0.336157,4.450431e-02,5.536993e-03,-0.261841,18.654374
1,NumInqLast6M,1,"[0.50, 1.50)",664,0.251897,344,320,0.481928,0.038934,3.816602e-04,4.770451e-05,-0.261841,21.488233
2,NumInqLast6M,2,"[1.50, 2.50)",426,0.161608,223,203,0.476526,0.060579,5.925881e-04,7.406219e-05,-0.261841,21.651765
3,NumInqLast6M,3,"[2.50, 4.50)",328,0.124431,201,127,0.387195,0.425731,2.214063e-02,2.746866e-03,-0.261841,24.410534
4,NumInqLast6M,4,"[4.50, inf)",173,0.065630,128,45,0.260116,1.011981,6.152860e-02,7.378823e-03,-0.261841,28.839726
5,NumInqLast6M,5,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.261841,21.194085
6,NumInqLast6M,6,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.261841,21.194085
0,NumInqLast6Mexcl7days,0,"(-inf, 0.50)",1096,0.415781,477,619,0.564781,-0.293976,3.576313e-02,4.454363e-03,0.041168,21.543283
1,NumInqLast6Mexcl7days,1,"[0.50, 1.50)",667,0.253035,341,326,0.488756,0.011598,3.403343e-05,4.254155e-06,0.041168,21.180308
2,NumInqLast6Mexcl7days,2,"[1.50, 2.50)",390,0.147951,204,186,0.476923,0.058986,5.143775e-04,6.428787e-05,0.041168,21.124018
3,NumInqLast6Mexcl7days,3,"[2.50, 4.50)",320,0.121396,200,120,0.375000,0.477439,2.705222e-02,3.349771e-03,0.041168,20.626961
4,NumInqLast6Mexcl7days,4,"[4.50, inf)",163,0.061836,118,45,0.276074,0.930635,4.963773e-02,5.990076e-03,0.041168,20.088633
5,NumInqLast6Mexcl7days,5,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.041168,21.194085
6,NumInqLast6Mexcl7days,6,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.041168,21.194085
0,NetFractionRevolvingBurden,0,"(-inf, 6.50)",676,0.256449,223,453,0.670118,-0.742107,1.358941e-01,1.660739e-02,-0.472229,11.082396
1,NetFractionRevolvingBurden,1,"[6.50, 14.50)",303,0.114947,104,199,0.656766,-0.682301,5.181219e-02,6.353750e-03,-0.472229,11.897297
2,NetFractionRevolvingBurden,2,"[14.50, 20.50)",200,0.075873,81,119,0.595000,-0.418061,1.311593e-02,1.627656e-03,-0.472229,15.497731
3,NetFractionRevolvingBurden,3,"[20.50, 26.50)",156,0.059181,68,88,0.564103,-0.291216,4.995803e-03,6.222780e-04,-0.472229,17.226078
4,NetFractionRevolvingBurden,4,"[26.50, 39.50)",347,0.131639,194,153,0.440922,0.204033,5.451883e-03,6.803057e-04,-0.472229,23.974168
5,NetFractionRevolvingBurden,5,"[39.50, 54.50)",333,0.126328,202,131,0.393393,0.399683,1.985068e-02,2.464950e-03,-0.472229,26.640027
6,NetFractionRevolvingBurden,6,"[54.50, 65.50)",182,0.069044,114,68,0.373626,0.483304,1.575836e-02,1.950844e-03,-0.472229,27.779408
7,NetFractionRevolvingBurden,7,"[65.50, 75.50)",164,0.062215,128,36,0.219512,1.235124,8.367301e-02,9.841209e-03,-0.472229,38.023446
8,NetFractionRevolvingBurden,8,"[75.50, inf)",275,0.104325,226,49,0.178182,1.495328,1.956607e-01,2.240670e-02,-0.472229,41.568884
9,NetFractionRevolvingBurden,9,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.472229,21.194085
10,NetFractionRevolvingBurden,10,Missing,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.472229,21.194085
0,NetFractionInstallBurden,0,"(-inf, 7.50)",940,0.356601,428,512,0.544681,-0.212588,1.608417e-02,2.006744e-03,-0.110599,20.515671
1,NetFractionInstallBurden,1,"[7.50, 33.50)",150,0.056904,55,95,0.633333,-0.579931,1.870723e-02,2.306176e-03,-0.110599,19.343407
2,NetFractionInstallBurden,2,"[33.50, 61.50)",401,0.152124,199,202,0.503741,-0.048350,3.556973e-04,4.445783e-05,-0.110599,21.039790
3,NetFractionInstallBurden,3,"[61.50, 72.50)",239,0.090668,133,106,0.443515,0.193523,3.379610e-03,4.217933e-04,-0.110599,21.811657
4,NetFractionInstallBurden,4,"[72.50, 93.50)",673,0.255311,380,293,0.435364,0.226612,1.303059e-02,1.625347e-03,-0.110599,21.917249
5,NetFractionInstallBurden,5,"[93.50, inf)",233,0.088392,145,88,0.377682,0.466010,1.878380e-02,2.326957e-03,-0.110599,22.681218
6,NetFractionInstallBurden,6,Special,0,0.000000,0,0,0.000000,0.000000,0.000000e+00,0.000000e+00,-0.110599,21.194085

In [484]:
at.writre_production_code(bp, scorecard, "scoring.py")

'F:\\datascience\\dsa-agent\\predictive-model-agent\\notebook\\scoring.py'

In [485]:
df.iloc[0][cols_feat].to_dict()

{'ExternalRiskEstimate': 55,
 'MSinceOldestTradeOpen': 144,
 'MSinceMostRecentTradeOpen': 4,
 'AverageMInFile': 84,
 'NumSatisfactoryTrades': 20,
 'NumTrades60Ever2DerogPubRec': 3,
 'NumTrades90Ever2DerogPubRec': 0,
 'PercentTradesNeverDelq': 83,
 'MSinceMostRecentDelq': 2,
 'MaxDelq2PublicRecLast12M': 3,
 'MaxDelqEver': 5,
 'NumTotalTrades': 23,
 'NumTradesOpeninLast12M': 1,
 'PercentInstallTrades': 43,
 'MSinceMostRecentInqexcl7days': 0,
 'NumInqLast6M': 0,
 'NumInqLast6Mexcl7days': 0,
 'NetFractionRevolvingBurden': 33,
 'NetFractionInstallBurden': -8,
 'NumRevolvingTradesWBalance': 8,
 'NumInstallTradesWBalance': 1,
 'NumBank2NatlTradesWHighUtilization': 1,
 'PercentTradesWBalance': 69}

In [486]:
df[col_score] = -scorecard.score(df[cols_feat])

In [487]:
at.scorecard_plot_cap(df.loc[df[col_type]!='train'], col_target, col_score, scorecard, 'cap.png')

In [488]:
at.scorecard_plot_auc_roc(df.loc[df[col_type]!='train'], col_target, col_score, scorecard, 'auc_roc.png')

In [489]:
at.scorecard_plot_ks(df.loc[df[col_type]!='train'], col_target, col_score, scorecard, 'ks.png')

In [490]:
from scoring import get_woe, get_score


dict_feat = {'ExternalRiskEstimate': 55,
 'MSinceOldestTradeOpen': 144,
 'MSinceMostRecentTradeOpen': 4,
 'AverageMInFile': 84,
 'NumSatisfactoryTrades': 20,
 'NumTrades60Ever2DerogPubRec': 3,
 'NumTrades90Ever2DerogPubRec': 0,
 'PercentTradesNeverDelq': 83,
 'MSinceMostRecentDelq': 2,
 'MaxDelq2PublicRecLast12M': 3,
 'MaxDelqEver': 5,
 'NumTotalTrades': 23,
 'NumTradesOpeninLast12M': 1,
 'PercentInstallTrades': 43,
 'MSinceMostRecentInqexcl7days': 0,
 'NumInqLast6M': 0,
 'NumInqLast6Mexcl7days': 0,
 'NetFractionRevolvingBurden': 33,
 'NetFractionInstallBurden': -8,
 'NumRevolvingTradesWBalance': 8,
 'NumInstallTradesWBalance': 1,
 'NumBank2NatlTradesWHighUtilization': 1,
 'PercentTradesWBalance': 69}

In [491]:
get_woe(dict_feat)

{'ExternalRiskEstimate': 1.219375952462631,
 'MSinceOldestTradeOpen': 0.055166381308707976,
 'MSinceMostRecentTradeOpen': 0.06857791062395104,
 'AverageMInFile': -0.2847014443136433,
 'NumSatisfactoryTrades': -0.11120403838954482,
 'NumTrades60Ever2DerogPubRec': 0.9825335567902594,
 'NumTrades90Ever2DerogPubRec': -0.1799432881288305,
 'PercentTradesNeverDelq': 0.9802320598019799,
 'MSinceMostRecentDelq': 1.1452679803089092,
 'MaxDelq2PublicRecLast12M': 0.9591187666408247,
 'MaxDelqEver': 0.6643368315546199,
 'NumTotalTrades': -0.009856518622543019,
 'NumTradesOpeninLast12M': -0.033387016032737055,
 'PercentInstallTrades': 0.07783861907748735,
 'MSinceMostRecentInqexcl7days': 0.42614531334570316,
 'NumInqLast6M': -0.3361573881357198,
 'NumInqLast6Mexcl7days': -0.29397579782899186,
 'NetFractionRevolvingBurden': 0.20403322163815557,
 'NetFractionInstallBurden': -0.21258844549044806,
 'NumRevolvingTradesWBalance': 0.6384827660799233,
 'NumInstallTradesWBalance': -0.08347112043014834,
 'NumBank2NatlTradesWHighUtilization': 0.25429505641904393,
 'PercentTradesWBalance': 0.13399296076301867}

In [492]:
get_score(dict_feat)

{'score': 541.4297875603456}